import { Category } from "../types";

export const initialCategories: Category[] = [
  {
    id: "cat-image-gen",
    name: "Image Generation",
    slug: "image-generation",
    description: "Expert prompts for photorealistic product photography, studio portraits, architecture, and conceptual art.",
    iconName: "Camera",
    accentColor: "from-amber-500/20 to-orange-500/20 text-amber-400 border-amber-500/30",
    templateCount: 5,
    imageUrl: "/images/categories/image-gen.jpg",
    subcategories: [
      {
        id: "sub-img-product",
        name: "Product Photography",
        slug: "product-photography",
        description: "Studio lighting, clean backdrops, and commercial aesthetic for physical items.",
        categoryId: "cat-image-gen",
        templateCount: 2,
      },
      {
        id: "sub-img-portraits",
        name: "Portraits & Characters",
        slug: "portraits-characters",
        description: "Editorial fashion, cinematic character close-ups, and stylistic human subjects.",
        categoryId: "cat-image-gen",
        templateCount: 1,
      },
      {
        id: "sub-img-architecture",
        name: "Architecture & Interiors",
        slug: "architecture-interiors",
        description: "Modern interior design, brutalist exteriors, and luxury spaces.",
        categoryId: "cat-image-gen",
        templateCount: 1,
      },
      {
        id: "sub-img-conceptual",
        name: "Conceptual & Landscapes",
        slug: "conceptual-landscapes",
        description: "Surreal dreamscapes, atmospheric environments, and artistic compositions.",
        categoryId: "cat-image-gen",
        templateCount: 1,
      },
    ],
  },
  {
    id: "cat-video-gen",
    name: "Video Generation",
    slug: "video-generation",
    description: "Motion-tuned prompts tailored for Runway, Sora, and Pika with camera direction, lighting, and pacing.",
    iconName: "Film",
    accentColor: "from-purple-500/20 to-indigo-500/20 text-purple-400 border-purple-500/30",
    templateCount: 10,
    imageUrl: "/images/categories/video-gen.jpg",
    subcategories: [
      {
        id: "sub-vid-cinematic",
        name: "Cinematic & B-Roll",
        slug: "cinematic-b-roll",
        description: "Slow-motion drone sweeps, cinematic camera pans, and documentary depth of field.",
        categoryId: "cat-video-gen",
        templateCount: 5,
      },
      {
        id: "sub-vid-product",
        name: "Product Videos",
        slug: "product-videos",
        description: "Commercial product showcases, macro pans, and high-fidelity 3D motion reveals.",
        categoryId: "cat-video-gen",
        templateCount: 4,
      },
      {
        id: "sub-vid-commercial",
        name: "Commercial & Product Motion",
        slug: "commercial-product-motion",
        description: "Dynamic product reveals, 360 spins, and advertising liquid splashes.",
        categoryId: "cat-video-gen",
        templateCount: 3,
      },
      {
        id: "sub-vid-fashion",
        name: "Fashion & Pacing",
        slug: "fashion-pacing",
        description: "High fashion transitions, slow walk movements, and editorial spotlighting.",
        categoryId: "cat-video-gen",
        templateCount: 2,
      },
    ],
  },
  {
    id: "cat-website-making",
    name: "Website Making",
    slug: "website-making",
    description: "Structure, copy, and layout prompts for modern AI web builders like v0, Framer, and Lovable.",
    iconName: "Globe",
    accentColor: "from-blue-500/20 to-cyan-500/20 text-blue-400 border-blue-500/30",
    templateCount: 4,
    imageUrl: "/images/categories/website-making.jpg",
    subcategories: [
      {
        id: "sub-web-landing",
        name: "Landing Pages",
        slug: "landing-pages",
        description: "Conversion-focused landing pages, hero layouts, and marketing sites.",
        categoryId: "cat-website-making",
        templateCount: 4,
      },
      {
        id: "sub-web-saas",
        name: "SaaS & Tech Landing Pages",
        slug: "saas-landing-pages",
        description: "Conversion-optimized dark mode hero sections, feature grids, and pricing calculators.",
        categoryId: "cat-website-making",
        templateCount: 2,
      },
      {
        id: "sub-web-ecommerce",
        name: "E-Commerce & Portfolios",
        slug: "ecommerce-portfolios",
        description: "Boutique storefronts, artisan galleries, and creative agency showcases.",
        categoryId: "cat-website-making",
        templateCount: 1,
      },
      {
        id: "sub-web-dashboards",
        name: "App Dashboards & UI",
        slug: "app-dashboards-ui",
        description: "Financial analytics cards, sidebar navigations, and real-time metric graphs.",
        categoryId: "cat-website-making",
        templateCount: 1,
      },
    ],
  },
  {
    id: "cat-slides-presentations",
    name: "Slides & Presentations",
    slug: "slides-presentations",
    description: "Slide narrative, layout architecture, and visual styling prompts for Gamma, Tome, and Beautiful.ai.",
    iconName: "Presentation",
    accentColor: "from-emerald-500/20 to-teal-500/20 text-emerald-400 border-emerald-500/30",
    templateCount: 7,
    imageUrl: "/images/categories/slides.jpg",
    subcategories: [
      {
        id: "sub-slides-pitch",
        name: "Pitch Decks & Fundraising",
        slug: "pitch-decks-fundraising",
        description: "10-slide VC narrative flow, market sizing breakdowns, and traction charts.",
        categoryId: "cat-slides-presentations",
        templateCount: 2,
      },
      {
        id: "sub-slides-corporate",
        name: "Executive & QBR Briefings",
        slug: "executive-qbr-briefings",
        description: "Quarterly review data visualizers, corporate strategy, and KPI scorecards.",
        categoryId: "cat-slides-presentations",
        templateCount: 4,
      },
      {
        id: "sub-slides-keynote",
        name: "Keynotes & Product Launches",
        slug: "keynotes-product-launches",
        description: "Bold typographic statements, minimalist hero slides, and product unveilings.",
        categoryId: "cat-slides-presentations",
        templateCount: 1,
      },
    ],
  },
  {
    id: "cat-poster-design",
    name: "Poster & Design",
    slug: "poster-design",
    description: "Graphic design prompts covering Swiss typography, music event flyers, brand identity, and packaging.",
    iconName: "Palette",
    accentColor: "from-rose-500/20 to-pink-500/20 text-rose-400 border-rose-500/30",
    templateCount: 8,
    imageUrl: "/images/categories/poster.jpg",
    subcategories: [
      {
        id: "sub-poster-social",
        name: "Social Media",
        slug: "social-media",
        description: "Engaging social media advertisement designs, stories, carousels, and promotional banners.",
        categoryId: "cat-poster-design",
        templateCount: 5,
      },
      {
        id: "sub-poster-events",
        name: "Music & Cultural Events",
        slug: "music-cultural-events",
        description: "Electronic music festival posters, vintage typography, and modern grid compositions.",
        categoryId: "cat-poster-design",
        templateCount: 4,
      },
      {
        id: "sub-poster-branding",
        name: "Brandboards & Visual Identity",
        slug: "brandboards-visual-identity",
        description: "Logo lockups, packaging mockups, and corporate stationery layouts.",
        categoryId: "cat-poster-design",
        templateCount: 3,
      },
      {
        id: "sub-poster-retro",
        name: "Retro & Synthwave",
        slug: "retro-synthwave",
        description: "80s neon chrome aesthetics, screenprint textures, and halftone gradients.",
        categoryId: "cat-poster-design",
        templateCount: 1,
      },
    ],
  },
];
