import { FeedbackEntry } from "../types";

export const initialFeedback: FeedbackEntry[] = [
  {
    id: "fb-1",
    templateId: "template-candle-photo",
    templateName: "Product Photography — Handmade Candle",
    userId: "user-101",
    userEmail: "praveen.studio@gmail.com",
    rating: "up",
    comment: "Pasted straight into Midjourney v6.1 and the warm waxy translucent glow on the candle was stunning! Used it on my Shopify store today.",
    toolUsed: "Midjourney v6.1",
    promptType: "base",
    createdAt: "2026-03-08T14:20:00Z",
  },
  {
    id: "fb-2",
    templateId: "template-candle-photo",
    templateName: "Product Photography — Handmade Candle",
    userId: "user-102",
    userEmail: "ananya.ceramics@crafts.in",
    rating: "up",
    comment: "I customized it with AI to add a dark granite surface instead of limestone, and the rewrite preserved all the Hasselblad camera settings perfectly.",
    toolUsed: "Midjourney v6.1",
    promptType: "customized",
    customizationRequestText: "Change the limestone pedestal to a rough dark polished black granite pedestal and add subtle smoke curling from the wick",
    createdAt: "2026-03-08T16:45:00Z",
  },
  {
    id: "fb-3",
    templateId: "template-web-saas-dark",
    templateName: "Dark Mode AI SaaS Landing Page with Pricing Matrix",
    userId: "user-103",
    userEmail: "dev@neotech.ai",
    rating: "up",
    comment: "Ran this through v0 and had a working Next.js page within 2 minutes. The pricing toggle worked out of the box.",
    toolUsed: "v0 by Vercel",
    promptType: "base",
    createdAt: "2026-03-09T09:12:00Z",
  },
  {
    id: "fb-4",
    templateId: "template-video-drone-mountains",
    templateName: "Cinematic Misty Mountain Drone Sweep",
    userId: "user-104",
    userEmail: "rohit.film@mumbai.com",
    rating: "up",
    comment: "Runway Gen-3 followed the forward pan motion instructions cleanly. Great volumetric rays.",
    toolUsed: "Runway Gen-3 Alpha",
    promptType: "base",
    createdAt: "2026-03-09T11:30:00Z",
  },
  {
    id: "fb-5",
    templateId: "template-luxury-watch",
    templateName: "Luxury Chronograph Watch on Dark Carbon",
    userId: "user-105",
    userEmail: "aditya.k@luxbrand.com",
    rating: "down",
    comment: "Midjourney sometimes drew extra hands on the sub-dials. Had to regenerate twice, but lighting was very good.",
    toolUsed: "Midjourney v6.1",
    promptType: "base",
    createdAt: "2026-03-09T13:00:00Z",
  },
];
