import { SubscriptionPlanItem, CountryConfig, PlanFeature } from "../types";

export const SUPPORTED_COUNTRIES: CountryConfig[] = [
  {
    code: "IN",
    name: "India",
    flag: "🇮🇳",
    currency: "INR",
    currencySymbol: "₹",
    defaultTax: "18% GST Included",
    region: "asia",
  },
  {
    code: "AE",
    name: "UAE",
    flag: "🇦🇪",
    currency: "AED",
    currencySymbol: "AED ",
    defaultTax: "5% VAT Included",
    region: "gcc",
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    flag: "🇸🇦",
    currency: "SAR",
    currencySymbol: "SAR ",
    defaultTax: "15% VAT Included",
    region: "gcc",
  },
  {
    code: "QA",
    name: "Qatar",
    flag: "🇶🇦",
    currency: "QAR",
    currencySymbol: "QAR ",
    defaultTax: "0% VAT",
    region: "gcc",
  },
  {
    code: "KW",
    name: "Kuwait",
    flag: "🇰🇼",
    currency: "KWD",
    currencySymbol: "KD ",
    defaultTax: "0% VAT",
    region: "gcc",
  },
  {
    code: "OM",
    name: "Oman",
    flag: "🇴🇲",
    currency: "OMR",
    currencySymbol: "OMR ",
    defaultTax: "5% VAT Included",
    region: "gcc",
  },
  {
    code: "BH",
    name: "Bahrain",
    flag: "🇧🇭",
    currency: "BHD",
    currencySymbol: "BD ",
    defaultTax: "10% VAT Included",
    region: "gcc",
  },
  {
    code: "US",
    name: "United States",
    flag: "🇺🇸",
    currency: "USD",
    currencySymbol: "$",
    defaultTax: "Tax calculated at checkout",
    region: "americas",
  },
  {
    code: "GB",
    name: "United Kingdom",
    flag: "🇬🇧",
    currency: "GBP",
    currencySymbol: "£",
    defaultTax: "20% VAT Included",
    region: "europe",
  },
  {
    code: "SG",
    name: "Singapore",
    flag: "🇸🇬",
    currency: "SGD",
    currencySymbol: "S$",
    defaultTax: "9% GST Included",
    region: "asia",
  },
  {
    code: "DE",
    name: "Germany / EU",
    flag: "🇪🇺",
    currency: "EUR",
    currencySymbol: "€",
    defaultTax: "19% VAT Included",
    region: "europe",
  },
  {
    code: "CA",
    name: "Canada",
    flag: "🇨🇦",
    currency: "CAD",
    currencySymbol: "CA$",
    defaultTax: "Tax calculated at checkout",
    region: "americas",
  },
  {
    code: "AU",
    name: "Australia",
    flag: "🇦🇺",
    currency: "AUD",
    currencySymbol: "A$",
    defaultTax: "10% GST Included",
    region: "asia",
  },
];

export const STANDARD_FEATURE_PRESETS: Omit<PlanFeature, "id">[] = [
  {
    name: "AI Generations",
    description: "Monthly AI prompt execution and benchmark generation runs",
    value: "Unlimited",
    enabled: true,
  },
  {
    name: "Workflow Templates",
    description: "Access to curated visual workflow canvas pipelines",
    value: "All 50+ Guides",
    enabled: true,
  },
  {
    name: "AI Assistant & Rewriter",
    description: "On-demand voice and text prompt fine-tuning copilot",
    value: "Priority Copilot",
    enabled: true,
  },
  {
    name: "Team Members",
    description: "Collaborative workspace seats for creators and designers",
    value: "3 Seats",
    enabled: true,
  },
  {
    name: "Cloud Storage",
    description: "Secure storage for custom prompts, assets, and version logs",
    value: "50 GB",
    enabled: true,
  },
  {
    name: "Commercial License",
    description: "Full commercial exploitation rights for generated prompt assets",
    value: "Included",
    enabled: true,
  },
  {
    name: "High-Res Benchmarks",
    description: "Uncompressed 4K reference images and 1080p preview videos",
    value: "4K ProRes",
    enabled: true,
  },
  {
    name: "MCP Server Sync",
    description: "Direct deep-linking into Midjourney, Flux, Sora & v0",
    value: "Direct Launch",
    enabled: true,
  },
  {
    name: "Priority Support",
    description: "Direct email and community channel priority SLA response",
    value: "24/7 SLA",
    enabled: true,
  },
];

// STRICTLY 2 PLANS: Monthly and Lifetime
export const initialSubscriptionPlans: SubscriptionPlanItem[] = [
  {
    id: "plan-monthly",
    name: "Monthly Plan",
    slug: "monthly",
    description: "Flexible month-to-month access to all AWA AI prompts, workflow guides, MCP server tokens, and tool launches.",
    badge: "Flexible",
    billingPeriod: "monthly",
    status: "active",
    subscribersCount: 842,
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-03-25T12:00:00Z",
    features: [
      {
        id: "feat-m1",
        name: "AI Generations",
        description: "Uncapped monthly creation iterations",
        value: "Unlimited",
        enabled: true,
      },
      {
        id: "feat-m2",
        name: "Workflow Templates",
        description: "Access to all 50+ step-by-step workflow blueprints",
        value: "All 50+ Guides",
        enabled: true,
      },
      {
        id: "feat-m3",
        name: "AI Assistant & Rewriter",
        description: "On-demand prompt fine-tuning & adaptation copilot",
        value: "Priority Copilot",
        enabled: true,
      },
      {
        id: "feat-m4",
        name: "Team Members",
        description: "Collaborative seats for client projects",
        value: "3 Seats",
        enabled: true,
      },
      {
        id: "feat-m5",
        name: "Cloud Storage",
        description: "Encrypted asset vault & version history logs",
        value: "25 GB",
        enabled: true,
      },
      {
        id: "feat-m6",
        name: "Commercial License",
        description: "Full commercial authorization for client deliveries",
        value: "Included",
        enabled: true,
      },
      {
        id: "feat-m7",
        name: "MCP Server Integration",
        description: "Direct deep-linking into Midjourney, Flux & Sora",
        value: "Direct Launch",
        enabled: true,
      },
    ],
    countryPricing: [
      {
        id: "cp-monthly-in",
        country: "India",
        countryCode: "IN",
        currency: "INR",
        currencySymbol: "₹",
        price: 499,
        discountedPrice: undefined,
        tax: "18% GST Included",
        billingPeriod: "monthly",
        status: "active",
      },
      {
        id: "cp-monthly-ae",
        country: "UAE",
        countryCode: "AE",
        currency: "AED",
        currencySymbol: "AED ",
        price: 29,
        discountedPrice: undefined,
        tax: "5% VAT Included",
        billingPeriod: "monthly",
        status: "active",
      },
      {
        id: "cp-monthly-sa",
        country: "Saudi Arabia",
        countryCode: "SA",
        currency: "SAR",
        currencySymbol: "SAR ",
        price: 39,
        discountedPrice: undefined,
        tax: "15% VAT Included",
        billingPeriod: "monthly",
        status: "active",
      },
      {
        id: "cp-monthly-qa",
        country: "Qatar",
        countryCode: "QA",
        currency: "QAR",
        currencySymbol: "QAR ",
        price: 39,
        discountedPrice: undefined,
        tax: "0% VAT",
        billingPeriod: "monthly",
        status: "active",
      },
      {
        id: "cp-monthly-kw",
        country: "Kuwait",
        countryCode: "KW",
        currency: "KWD",
        currencySymbol: "KD ",
        price: 3.5,
        discountedPrice: undefined,
        tax: "0% VAT",
        billingPeriod: "monthly",
        status: "active",
      },
      {
        id: "cp-monthly-om",
        country: "Oman",
        countryCode: "OM",
        currency: "OMR",
        currencySymbol: "OMR ",
        price: 4,
        discountedPrice: undefined,
        tax: "5% VAT Included",
        billingPeriod: "monthly",
        status: "active",
      },
      {
        id: "cp-monthly-bh",
        country: "Bahrain",
        countryCode: "BH",
        currency: "BHD",
        currencySymbol: "BD ",
        price: 3.9,
        discountedPrice: undefined,
        tax: "10% VAT Included",
        billingPeriod: "monthly",
        status: "active",
      },
      {
        id: "cp-monthly-us",
        country: "United States",
        countryCode: "US",
        currency: "USD",
        currencySymbol: "$",
        price: 9.99,
        discountedPrice: undefined,
        tax: "Taxes at checkout",
        billingPeriod: "monthly",
        status: "active",
      },
      {
        id: "cp-monthly-gb",
        country: "United Kingdom",
        countryCode: "GB",
        currency: "GBP",
        currencySymbol: "£",
        price: 7.99,
        discountedPrice: undefined,
        tax: "20% VAT Included",
        billingPeriod: "monthly",
        status: "active",
      },
      {
        id: "cp-monthly-sg",
        country: "Singapore",
        countryCode: "SG",
        currency: "SGD",
        currencySymbol: "S$",
        price: 12.99,
        discountedPrice: undefined,
        tax: "9% GST Included",
        billingPeriod: "monthly",
        status: "active",
      },
      {
        id: "cp-monthly-de",
        country: "Germany / EU",
        countryCode: "DE",
        currency: "EUR",
        currencySymbol: "€",
        price: 9.99,
        discountedPrice: undefined,
        tax: "19% VAT Included",
        billingPeriod: "monthly",
        status: "active",
      },
      {
        id: "cp-monthly-ca",
        country: "Canada",
        countryCode: "CA",
        currency: "CAD",
        currencySymbol: "CA$",
        price: 12.99,
        discountedPrice: undefined,
        tax: "Taxes at checkout",
        billingPeriod: "monthly",
        status: "active",
      },
      {
        id: "cp-monthly-au",
        country: "Australia",
        countryCode: "AU",
        currency: "AUD",
        currencySymbol: "A$",
        price: 14.99,
        discountedPrice: undefined,
        tax: "10% GST Included",
        billingPeriod: "monthly",
        status: "active",
      },
    ],
  },
  {
    id: "plan-lifetime",
    name: "Lifetime Plan",
    slug: "lifetime",
    description: "One-time investment for perpetual unlimited platform access, grandfathered access to all future workflow drops, and Founder Hall status.",
    badge: "Best Value",
    billingPeriod: "lifetime",
    status: "active",
    subscribersCount: 621,
    createdAt: "2026-01-15T08:00:00Z",
    updatedAt: "2026-03-26T14:30:00Z",
    features: [
      {
        id: "feat-l1",
        name: "Perpetual Access Forever",
        description: "Zero recurring renewals, never pay again",
        value: "Lifetime",
        enabled: true,
      },
      {
        id: "feat-l2",
        name: "All Future Updates Included",
        description: "Grandfathered into every new workflow and AI engine update",
        value: "All Future Guides",
        enabled: true,
      },
      {
        id: "feat-l3",
        name: "Design Rocket VIP Masterclass",
        description: "Exclusive access to prompt engineering workshops",
        value: "VIP Masterclasses",
        enabled: true,
      },
      {
        id: "feat-l4",
        name: "Priority Support & Discord",
        description: "Direct channel to AWA core engineering team",
        value: "24/7 VIP Channel",
        enabled: true,
      },
      {
        id: "feat-l5",
        name: "Commercial Production Rights",
        description: "Full commercial client license with certificates",
        value: "Enterprise Rights",
        enabled: true,
      },
      {
        id: "feat-l6",
        name: "Team Members",
        description: "Generous allocation for your studio",
        value: "5 Seats",
        enabled: true,
      },
      {
        id: "feat-l7",
        name: "Cloud Storage",
        description: "High capacity storage vault",
        value: "100 GB",
        enabled: true,
      },
      {
        id: "feat-l8",
        name: "Founder Profile Badge",
        description: "Distinctive gold badge in prompt community",
        value: "Founder Status",
        enabled: true,
      },
    ],
    countryPricing: [
      {
        id: "cp-lifetime-in",
        country: "India",
        countryCode: "IN",
        currency: "INR",
        currencySymbol: "₹",
        price: 4999,
        discountedPrice: 3999,
        tax: "18% GST Included",
        billingPeriod: "lifetime",
        status: "active",
      },
      {
        id: "cp-lifetime-ae",
        country: "UAE",
        countryCode: "AE",
        currency: "AED",
        currencySymbol: "AED ",
        price: 299,
        discountedPrice: undefined,
        tax: "5% VAT Included",
        billingPeriod: "lifetime",
        status: "active",
      },
      {
        id: "cp-lifetime-sa",
        country: "Saudi Arabia",
        countryCode: "SA",
        currency: "SAR",
        currencySymbol: "SAR ",
        price: 399,
        discountedPrice: 349,
        tax: "15% VAT Included",
        billingPeriod: "lifetime",
        status: "active",
      },
      {
        id: "cp-lifetime-qa",
        country: "Qatar",
        countryCode: "QA",
        currency: "QAR",
        currencySymbol: "QAR ",
        price: 399,
        discountedPrice: undefined,
        tax: "0% VAT",
        billingPeriod: "lifetime",
        status: "active",
      },
      {
        id: "cp-lifetime-kw",
        country: "Kuwait",
        countryCode: "KW",
        currency: "KWD",
        currencySymbol: "KD ",
        price: 32,
        discountedPrice: undefined,
        tax: "0% VAT",
        billingPeriod: "lifetime",
        status: "active",
      },
      {
        id: "cp-lifetime-om",
        country: "Oman",
        countryCode: "OM",
        currency: "OMR",
        currencySymbol: "OMR ",
        price: 40,
        discountedPrice: undefined,
        tax: "5% VAT Included",
        billingPeriod: "lifetime",
        status: "active",
      },
      {
        id: "cp-lifetime-bh",
        country: "Bahrain",
        countryCode: "BH",
        currency: "BHD",
        currencySymbol: "BD ",
        price: 39,
        discountedPrice: undefined,
        tax: "10% VAT Included",
        billingPeriod: "lifetime",
        status: "active",
      },
      {
        id: "cp-lifetime-us",
        country: "United States",
        countryCode: "US",
        currency: "USD",
        currencySymbol: "$",
        price: 99.0,
        discountedPrice: 79.0,
        tax: "Taxes at checkout",
        billingPeriod: "lifetime",
        status: "active",
      },
      {
        id: "cp-lifetime-gb",
        country: "United Kingdom",
        countryCode: "GB",
        currency: "GBP",
        currencySymbol: "£",
        price: 79.0,
        discountedPrice: undefined,
        tax: "20% VAT Included",
        billingPeriod: "lifetime",
        status: "active",
      },
      {
        id: "cp-lifetime-sg",
        country: "Singapore",
        countryCode: "SG",
        currency: "SGD",
        currencySymbol: "S$",
        price: 129.0,
        discountedPrice: undefined,
        tax: "9% GST Included",
        billingPeriod: "lifetime",
        status: "active",
      },
      {
        id: "cp-lifetime-de",
        country: "Germany / EU",
        countryCode: "DE",
        currency: "EUR",
        currencySymbol: "€",
        price: 89.0,
        discountedPrice: undefined,
        tax: "19% VAT Included",
        billingPeriod: "lifetime",
        status: "active",
      },
      {
        id: "cp-lifetime-ca",
        country: "Canada",
        countryCode: "CA",
        currency: "CAD",
        currencySymbol: "CA$",
        price: 129.0,
        discountedPrice: undefined,
        tax: "Taxes at checkout",
        billingPeriod: "lifetime",
        status: "active",
      },
      {
        id: "cp-lifetime-au",
        country: "Australia",
        countryCode: "AU",
        currency: "AUD",
        currencySymbol: "A$",
        price: 149.0,
        discountedPrice: undefined,
        tax: "10% GST Included",
        billingPeriod: "lifetime",
        status: "active",
      },
    ],
  },
];

export function getCountryConfig(countryNameOrCode: string): CountryConfig {
  const normalized = countryNameOrCode.trim().toLowerCase();
  if (normalized === "united arab emirates" || normalized === "uae") {
    const uae = SUPPORTED_COUNTRIES.find((c) => c.code === "AE" || c.name === "UAE");
    if (uae) return { ...uae, name: "United Arab Emirates" };
  }
  const match = SUPPORTED_COUNTRIES.find(
    (c) =>
      c.code.toLowerCase() === normalized ||
      c.name.toLowerCase() === normalized
  );
  if (match) return match;

  return {
    code: countryNameOrCode.slice(0, 2).toUpperCase() || "XX",
    name: countryNameOrCode,
    flag: "🌐",
    currency: "USD",
    currencySymbol: "$",
    defaultTax: "Tax excluded",
    region: "other",
  };
}

export function formatPriceWithCurrency(
  price: number,
  currencySymbol: string,
  currencyCode?: string
): string {
  if (price === 0) return "Free";
  const formatted = price.toLocaleString("en-US", {
    minimumFractionDigits: price % 1 === 0 ? 0 : 2,
    maximumFractionDigits: 2,
  });

  if (currencySymbol.endsWith(" ")) {
    return `${currencySymbol}${formatted}`;
  }
  return `${currencySymbol}${formatted}`;
}
