import { SupportRequest } from "@/lib/types";

export const initialSupportRequests: SupportRequest[] = [
  {
    id: "SUP-000124",
    subject: "Image generation issue using reference image in Kling",
    category: "AI Generation",
    priority: "high",
    status: "resolved",
    user: {
      id: "usr-101",
      name: "John Doe",
      email: "john.doe@creativestudio.ai",
      avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&h=120&fit=crop",
      plan: "Monthly Unlimited",
      country: "United States",
      deviceLimit: 3,
    },
    assignedTo: "adm-1",
    assignedAdminName: "Praveen (Lead Admin)",
    messages: [
      {
        id: "msg-1",
        sender: "John Doe",
        senderType: "user",
        message:
          "I am trying to generate a cinematic product video using the Image-to-Video guide with Kling. I uploaded the bottle reference image from Step 03, but the output video keeps distorting the label typography and introducing water-droplet artifacts that weren't in the prompt.",
        attachments: [
          {
            id: "att-1",
            name: "kling-artifact-frame.png",
            url: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800",
            type: "image/png",
            sizeFormatted: "1.4 MB",
          },
        ],
        createdAt: "2026-09-28T09:15:00Z",
      },
      {
        id: "msg-2",
        sender: "Praveen (Lead Admin)",
        senderType: "admin",
        message:
          "Hi John, thanks for reaching out. We analyzed the frame you attached. In Kling 1.5, when Motion Strength is set above 6, fine typographic labels on curved surfaces tend to deform. Could you please check your Motion Strength slider and set it to 3 or 4 with 'Camera: Slow Push-in'?",
        createdAt: "2026-09-28T09:42:00Z",
      },
      {
        id: "msg-3",
        sender: "John Doe",
        senderType: "user",
        message:
          "Thanks for the fast reply! I lowered the motion strength to 3.5. The label stayed much sharper. However, is there a recommended negative prompt I should include for the reflections?",
        createdAt: "2026-09-28T10:05:00Z",
      },
    ],
    internalNotes: [
      {
        id: "note-1",
        author: "Praveen (Lead Admin)",
        note: "Verified user account: Pro subscriber active since July 2026. Checked generation telemetry: User ran 4 variations with motionStrength=8. Recommended lowering to 3.5.",
        createdAt: "2026-09-28T09:30:00Z",
      },
    ],
    attachments: [
      {
        id: "att-1",
        name: "kling-artifact-frame.png",
        url: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800",
        type: "image/png",
        sizeFormatted: "1.4 MB",
      },
    ],
    resolutionSummary: "Advised user to lower motion strength to 3.5 and guided on reference frame settings in Kling.",
    resolvedAt: "2026-09-28T10:24:00Z",
    createdAt: "2026-09-28T10:24:00Z",
    updatedAt: "2026-09-28T10:24:00Z",
  },
  {
    id: "SUP-000125",
    subject: "Tax invoice / GST identification number needed for billing",
    category: "Billing",
    priority: "medium",
    status: "open",
    user: {
      id: "usr-102",
      name: "Sarah Jenkins",
      email: "sarah.j@apexdesign.co.uk",
      avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&h=120&fit=crop",
      plan: "Lifetime Access",
      country: "United Kingdom",
      deviceLimit: 5,
    },
    assignedTo: "unassigned",
    assignedAdminName: "Unassigned",
    messages: [
      {
        id: "msg-101",
        sender: "Sarah Jenkins",
        senderType: "user",
        message:
          "Hello AWA Finance team, I purchased the Lifetime Access plan yesterday through Stripe, but the email receipt doesn't include our company's VAT/GST registration number (GB987654321). Could you please regenerate our official invoice showing our corporate tax ID?",
        attachments: [
          {
            id: "att-101",
            name: "stripe-receipt-oct2026.pdf",
            url: "#",
            type: "application/pdf",
            sizeFormatted: "184 KB",
          },
        ],
        createdAt: "2026-09-28T09:12:00Z",
      },
    ],
    internalNotes: [
      {
        id: "note-101",
        author: "Finance Bot",
        note: "Stripe transaction id: ch_3P92jxK199. Payment verified: £149.00 GBP. Awaiting admin invoice generation.",
        createdAt: "2026-09-28T09:13:00Z",
      },
    ],
    attachments: [
      {
        id: "att-101",
        name: "stripe-receipt-oct2026.pdf",
        url: "#",
        type: "application/pdf",
        sizeFormatted: "184 KB",
      },
    ],
    createdAt: "2026-09-28T09:12:00Z",
    updatedAt: "2026-09-28T09:12:00Z",
  },
  {
    id: "SUP-000126",
    subject: "Urgent: Lifetime Plan not unlocking AI Customization Panel",
    category: "Subscription",
    priority: "urgent",
    status: "in-progress",
    user: {
      id: "usr-103",
      name: "Marcus Vance",
      email: "marcus.v@hyperionagency.com",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&h=120&fit=crop",
      plan: "Lifetime Access",
      country: "Germany",
      deviceLimit: 5,
    },
    assignedTo: "adm-2",
    assignedAdminName: "Amina",
    messages: [
      {
        id: "msg-201",
        sender: "Marcus Vance",
        senderType: "user",
        message:
          "I completed payment for Lifetime Access 30 minutes ago, but the template customizer is still showing the paywall lock card: 'Subscribe to Unlock Customization'. My account shows Lifetime in the header, but the API seems to think I am on Free tier.",
        createdAt: "2026-09-27T17:48:00Z",
      },
      {
        id: "msg-202",
        sender: "Amina",
        senderType: "admin",
        message:
          "Hello Marcus, our engineering team is actively investigating this. We noticed a brief webhook delay in token entitlement synchronization between Razorpay and our session cache. We are manually pushing an entitlement refresh to your account right now.",
        createdAt: "2026-09-27T18:05:00Z",
      },
    ],
    internalNotes: [
      {
        id: "note-201",
        author: "Amina",
        note: "Redis session entitlement was cached with old JWT. Invalidated cache key `user:usr-103:entitlements`. User can now access customizer.",
        createdAt: "2026-09-27T18:12:00Z",
      },
    ],
    createdAt: "2026-09-27T17:48:00Z",
    updatedAt: "2026-09-27T18:05:00Z",
  },
  {
    id: "SUP-000127",
    subject: "How to generate a new API key for integration?",
    category: "Technical",
    priority: "low",
    status: "pending",
    user: {
      id: "usr-104",
      name: "Emily Carter",
      email: "emily.c@brandhub.io",
      avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&h=120&fit=crop",
      plan: "Monthly Unlimited",
      country: "Canada",
      deviceLimit: 3,
    },
    assignedTo: "adm-3",
    assignedAdminName: "Rohit",
    messages: [
      {
        id: "msg-301",
        sender: "Emily Carter",
        senderType: "user",
        message:
          "Could you please guide me on how to create a new key for integration with our internal CMS pipeline?",
        createdAt: "2026-09-27T11:30:00Z",
      },
    ],
    internalNotes: [
      {
        id: "note-301",
        author: "Rohit",
        note: "Waiting for user confirmation on which CMS system they are using.",
        createdAt: "2026-09-27T11:35:00Z",
      },
    ],
    createdAt: "2026-09-27T11:30:00Z",
    updatedAt: "2026-09-27T11:30:00Z",
  },
  {
    id: "SUP-000128",
    subject: "Request for refund - duplicate payment",
    category: "Billing",
    priority: "medium",
    status: "open",
    user: {
      id: "usr-105",
      name: "David Kim",
      email: "david@pixelworks.com",
      avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&h=120&fit=crop",
      plan: "Monthly Unlimited",
      country: "South Korea",
      deviceLimit: 3,
    },
    assignedTo: "unassigned",
    assignedAdminName: "Unassigned",
    messages: [
      {
        id: "msg-401",
        sender: "David Kim",
        senderType: "user",
        message:
          "I was charged twice for the Pro plan. Please help cancel the second billing and process a refund.",
        createdAt: "2026-09-26T16:15:00Z",
      },
    ],
    internalNotes: [
      {
        id: "note-401",
        author: "Finance Team",
        note: "Verified duplicate transaction in Stripe dashboard. Awaiting admin approval to trigger refund.",
        createdAt: "2026-09-26T16:20:00Z",
      },
    ],
    createdAt: "2026-09-26T16:15:00Z",
    updatedAt: "2026-09-26T16:15:00Z",
  },
  {
    id: "SUP-000129",
    subject: "Multi-Language localization inquiry in prompt pipelines",
    category: "AI Generation",
    priority: "medium",
    status: "in-progress",
    user: {
      id: "usr-106",
      name: "Claire Dubois",
      email: "c.dubois@atelierdesign.paris",
      avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&h=120&fit=crop",
      plan: "Monthly Unlimited",
      country: "France",
      deviceLimit: 2,
    },
    assignedTo: "adm-1",
    assignedAdminName: "Praveen (Lead Admin)",
    messages: [
      {
        id: "msg-501",
        sender: "Claire Dubois",
        senderType: "user",
        message: "Bonjour! Is there any plan to support French language output when customizing prompts?",
        createdAt: "2026-09-26T11:00:00Z",
      },
      {
        id: "msg-502",
        sender: "Praveen (Lead Admin)",
        senderType: "admin",
        message: "Bonjour Claire! Yes, multi-language output is currently rolling out.",
        createdAt: "2026-09-26T14:30:00Z",
      },
    ],
    internalNotes: [],
    createdAt: "2026-09-26T11:00:00Z",
    updatedAt: "2026-09-26T14:30:00Z",
  },
  {
    id: "SUP-000130",
    subject: "Text contrast issue in Step Builder light mode dropdowns",
    category: "Bug Report",
    priority: "high",
    status: "open",
    user: {
      id: "usr-107",
      name: "Amina Al-Mansoor",
      email: "amina@dubaimedia.ae",
      avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&h=120&fit=crop",
      plan: "Lifetime Access",
      country: "United Arab Emirates",
      deviceLimit: 5,
    },
    assignedTo: "adm-2",
    assignedAdminName: "Amina",
    messages: [
      {
        id: "msg-601",
        sender: "Amina Al-Mansoor",
        senderType: "user",
        message:
          "In the Template Guide Builder, when set to Light Mode, some select triggers have white text on a very pale background.",
        createdAt: "2026-09-26T06:15:00Z",
      },
    ],
    internalNotes: [],
    createdAt: "2026-09-26T06:15:00Z",
    updatedAt: "2026-09-26T06:15:00Z",
  },
  {
    id: "SUP-000131",
    subject: "Custom MCP server setup documentation request",
    category: "Template / Guide",
    priority: "medium",
    status: "resolved",
    user: {
      id: "usr-108",
      name: "Liam O'Connor",
      email: "liam@techventures.ie",
      avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&h=120&fit=crop",
      plan: "Monthly Unlimited",
      country: "Ireland",
      deviceLimit: 3,
    },
    assignedTo: "adm-3",
    assignedAdminName: "Rohit",
    messages: [
      {
        id: "msg-701",
        sender: "Liam O'Connor",
        senderType: "user",
        message: "Hi team, does AWA provide an MCP connector guide?",
        createdAt: "2026-09-25T11:20:00Z",
      },
    ],
    internalNotes: [],
    resolutionSummary: "Shared documentation link and sample mcp_config.json configuration.",
    resolvedAt: "2026-09-25T12:00:00Z",
    createdAt: "2026-09-25T11:20:00Z",
    updatedAt: "2026-09-25T12:00:00Z",
  },
  {
    id: "SUP-000132",
    subject: "Full refund request within 7-day money-back guarantee period",
    category: "Billing",
    priority: "high",
    status: "resolved",
    user: {
      id: "usr-109",
      name: "Rajesh Sharma",
      email: "rajesh@sharmaconsulting.in",
      avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&h=120&fit=crop",
      plan: "Monthly Unlimited",
      country: "India",
      deviceLimit: 2,
    },
    assignedTo: "adm-3",
    assignedAdminName: "Rohit",
    messages: [
      {
        id: "msg-801",
        sender: "Rajesh Sharma",
        senderType: "user",
        message: "Processed refund inquiry per 7-day policy.",
        createdAt: "2026-09-25T14:00:00Z",
      },
    ],
    internalNotes: [],
    resolutionSummary: "Processed 100% prompt refund per 7-day policy.",
    resolvedAt: "2026-09-25T15:05:00Z",
    createdAt: "2026-09-25T14:00:00Z",
    updatedAt: "2026-09-25T15:05:00Z",
  },
  {
    id: "SUP-000133",
    subject: "Camera physics and prompt structure questions for Sora and Veo",
    category: "AI Generation",
    priority: "low",
    status: "closed",
    user: {
      id: "usr-110",
      name: "Taro Takahashi",
      email: "taro.t@tokyodesign.jp",
      avatarUrl: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=120&h=120&fit=crop",
      plan: "Lifetime Access",
      country: "Japan",
      deviceLimit: 4,
    },
    assignedTo: "unassigned",
    assignedAdminName: "Unassigned",
    messages: [
      {
        id: "msg-901",
        sender: "Taro Takahashi",
        senderType: "user",
        message: "Which prompt keywords yield the most realistic camera momentum?",
        createdAt: "2026-09-25T12:00:00Z",
      },
    ],
    internalNotes: [],
    closedAt: "2026-09-25T13:00:00Z",
    createdAt: "2026-09-25T12:00:00Z",
    updatedAt: "2026-09-25T13:00:00Z",
  },
];
