import { Template } from "../types";

export const initialTemplates: Template[] = [
  // ----------------------------------------------------
  // AWA OFFICIAL SHOWCASE TEMPLATES (Screenshot Featured)
  // ----------------------------------------------------
  {
    id: "template-dark-mode-ai-saas",
    name: "Dark Mode AI SaaS Landing Page",
    slug: "dark-mode-ai-saas-landing-page",
    categoryId: "cat-web-code",
    categoryName: "Saas",
    subcategoryId: "sub-web-saas",
    subcategoryName: "SaaS & Tech",
    description: "A high-converting modern landing page template tailored for v0 and Figma, featuring glassmorphism cards, interactive pricing toggle, and animated glow borders. Perfect for AI SaaS products, startups, and indie hackers.",
    promptText: "Design a high-converting modern dark mode AI SaaS landing page hero named NovaAI. Rich deep obsidian theme (#08090d) with subtle violet and indigo glowing mesh gradients. macOS window container with traffic lights. Clean navigation with NovaAI logo, Product, Features, Pricing, Blog links, Sign In, and 'Get Started' gradient CTA. Eyebrow badge 'AI Powered • v2.0'. Bold headline 'Build Smarter with AI' with purple highlight. Clear value proposition copy and dual CTAs: 'Get Started' and 'Watch Demo'. Floating glassmorphism real-time dashboard telemetry card with live requests metric (1.4M/hr), accuracy (99.8%), and animated purple-cyan gradient audio/bar visualizer. Four key proof metrics: '10K+ Happy Users', '3x Faster Development', '99% Uptime', '4.9/5 User Rating'. Built with React, Tailwind CSS, Lucide icons, and Framer Motion.",
    safePreviewText: "High-converting modern dark mode AI SaaS landing page with glassmorphism cards and live telemetry...",
    tags: ["landing page", "dark mode", "SaaS", "pricing", "v0", "Figma", "animation", "glassmorphism", "Hero", "Technology", "Ai", "All", "Recent"],
    difficulty: "Intermediate",
    style: "Glassmorphism",
    mood: "Modern & High-Converting",
    recommendedTools: [
      {
        toolId: "tool-v0",
        toolName: "v0 by Vercel",
        modelName: "v0 Generative UI",
        reason: "Generate and customize landing pages with AI",
        badge: "Flagship Match",
      },
      {
        toolId: "tool-figma",
        toolName: "Figma",
        modelName: "Figma Vector UI",
        reason: "Edit and design the UI components",
      },
      {
        toolId: "tool-chatgpt",
        toolName: "ChatGPT",
        modelName: "GPT-4o",
        reason: "Modify the prompt, generate content, and get variations",
      },
      {
        toolId: "tool-midjourney",
        toolName: "Midjourney",
        modelName: "v6 Photoreal",
        reason: "Create custom visuals, hero images, and illustrations",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Preview the Design",
        instruction: "Explore the preview images to understand the layout, sections, and style.",
      },
      {
        stepNumber: 2,
        title: "Choose Your Tool",
        instruction: "Use v0, Figma, or your preferred tool to start building.",
      },
      {
        stepNumber: 3,
        title: "Customize Content",
        instruction: "Replace text, images, and branding with your own.",
      },
      {
        stepNumber: 4,
        title: "Implement Features",
        instruction: "Add interactive elements like pricing toggle, animations, and forms.",
      },
      {
        stepNumber: 5,
        title: "Make it Responsive",
        instruction: "Ensure the design works well on all devices.",
      },
      {
        stepNumber: 6,
        title: "Launch Your Project",
        instruction: "Export or deploy to your preferred platform (Vercel, Netlify, etc.).",
      },
    ],
    thumbnailGradient: "from-purple-950 via-zinc-950 to-indigo-950",
    likesCount: 2400,
    savesCount: 1820,
    isPublished: true,
    createdAt: "2026-03-08T12:00:00Z",
  },
  {
    id: "template-consentinel",
    name: "ConSentinel",
    slug: "consentinel",
    categoryId: "cat-web-code",
    categoryName: "Motion",
    subcategoryId: "sub-web-saas",
    subcategoryName: "Motion",
    description: "Next-gen intelligent security platform landing experience featuring translucent iridescent glass sphere, real-time cyber telemetry, and fluid micro-interactions.",
    promptText: "Create a modern luxury cybersecurity SaaS landing page hero named ConSentinel with dark obsidian theme. Centered refractive translucent 3D glass orb with ambient refraction and chrome orbital ring. Metric pills showing '112+ Guarded Nodes' and '55K+ Shield Capacity', sleek glassmorphic card 'AI-Driven Protection', minimalist typography in Inter/Plus Jakarta Sans, subtle radiant neon backlighting, Lucide icons, responsive Tailwind CSS with framer-motion floating physics.",
    safePreviewText: "Commercial editorial cybersecurity SaaS landing page with refractive 3D glass sphere...",
    tags: ["Motion", "Apps", "Hero", "Saas", "Technology", "Cybersecurity", "Landing Page"],
    difficulty: "Intermediate",
    style: "Translucent Glassmorphism",
    mood: "Futuristic & Protective",
    recommendedTools: [
      {
        toolId: "tool-lovable",
        toolName: "Lovable",
        modelName: "Lovable Fullstack",
        reason: "Best for instant glassmorphism styling and live React state",
        badge: "Flagship Match",
      },
      {
        toolId: "tool-cursor",
        toolName: "Cursor",
        modelName: "Claude 3.7 Sonnet",
        reason: "Flawless Tailwind 3D orb styling & lucide telemetry",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Initialize in Lovable / Bolt",
        instruction: "Paste prompt into Lovable or Bolt.new to generate the glassmorphic cybersecurity hero.",
      },
      {
        stepNumber: 2,
        title: "Adjust Metrics & Spheres",
        instruction: "Fine-tune the 112+ and 55K+ telemetry metrics in the floating glass card.",
      },
    ],
    thumbnailGradient: "from-slate-900 via-blue-950 to-indigo-900",
    likesCount: 28,
    savesCount: 19,
    isPublished: true,
    createdAt: "2026-03-06T12:00:00Z",
  },
  {
    id: "template-anchor-ai",
    name: "Anchor AI",
    slug: "anchor-ai",
    categoryId: "cat-web-code",
    categoryName: "Portfolio",
    subcategoryId: "sub-web-portfolio",
    subcategoryName: "Portfolio",
    description: "Ultra-dark modern portfolio and AI research lab website featuring an interactive neon cyan wireframe 3D tesseract cube and minimal editorial typography.",
    promptText: "Design a high-end AI research studio and founder portfolio named Anchor AI. Deep jet-black background (#09090b) featuring an interactive glowing cyan wireframe cube with quantum particle trails. Headline 'Intelligence With Purpose', top navigation with pill buttons [Vision] [Models] [Analytics] [Repository], sleek Bento-grid metrics, smooth hover glow animations, built with Next.js, Three.js / Canvas, and Tailwind CSS.",
    safePreviewText: "AI research studio portfolio with glowing cyan wireframe cube and dark Bento grid...",
    tags: ["Portfolio", "Ai", "Sections", "Hero", "Saas", "Technology", "Recent"],
    difficulty: "Intermediate",
    style: "Cyber Wireframe & Dark Bento",
    mood: "Cerebral & Cutting-Edge",
    recommendedTools: [
      {
        toolId: "tool-cursor",
        toolName: "Cursor",
        modelName: "Claude 3.7 Sonnet",
        reason: "Best for Three.js / Canvas wireframe tesseract physics",
        badge: "Flagship Match",
      },
      {
        toolId: "tool-bolt",
        toolName: "Bolt.new",
        modelName: "Bolt WebContainer",
        reason: "Instant live preview of dynamic Bento grid layouts",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Spin Up 3D Canvas",
        instruction: "Drop the prompt into Cursor or Bolt to render the wireframe cube with mouse-tracking orbit.",
      },
      {
        stepNumber: 2,
        title: "Customize Bento Cards",
        instruction: "Populate the research vision, model weights, and publication links in the bento layout.",
      },
    ],
    thumbnailGradient: "from-zinc-950 via-slate-900 to-cyan-950",
    likesCount: 42,
    savesCount: 38,
    isPublished: true,
    createdAt: "2026-03-06T11:00:00Z",
  },
  {
    id: "template-3d-portfolio",
    name: "3D Portfolio",
    slug: "3d-portfolio",
    categoryId: "cat-web-code",
    categoryName: "Portfolio",
    subcategoryId: "sub-web-portfolio",
    subcategoryName: "Portfolio",
    description: "Interactive card stack portfolio interface for creative directors with layered numbered showcases ('01 CLIENT', '02 PERSONAL') and live tilt physics.",
    promptText: "Design an award-winning creative portfolio website with a multi-layered stacked card interface. Large bold numbers '01 CLIENT' (Nextlevel Studio) and '02 PERSONAL' (Aura Identity), live project preview thumbnails with rounded pill badges [LIVE PROJECT], smooth draggable stack gesture, dark graphite theme (#111114), glassmorphic control buttons, smooth page transitions in React and Tailwind CSS.",
    safePreviewText: "Layered stacked card portfolio for creative directors with 01 CLIENT / 02 PERSONAL...",
    tags: ["Portfolio", "Creative", "Apps", "Sections", "Recent"],
    difficulty: "Beginner",
    style: "Layered Card Stack",
    mood: "Editorial & Expressive",
    recommendedTools: [
      {
        toolId: "tool-lovable",
        toolName: "Lovable",
        modelName: "Lovable Fullstack",
        reason: "Smooth drag-and-drop card stack physics with Tailwind",
        badge: "Recommended",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Generate Card Stack",
        instruction: "Paste prompt into Lovable to scaffold the layered numbered card transitions.",
      },
      {
        stepNumber: 2,
        title: "Insert Case Studies",
        instruction: "Link your client and personal works into 01 CLIENT and 02 PERSONAL card decks.",
      },
    ],
    thumbnailGradient: "from-neutral-900 via-stone-900 to-zinc-900",
    likesCount: 35,
    savesCount: 29,
    isPublished: true,
    createdAt: "2026-03-06T10:00:00Z",
  },
  {
    id: "template-c-la-jewelry",
    name: "C*LA Jewelry",
    slug: "c-la-jewelry",
    categoryId: "cat-image-gen",
    categoryName: "Creative",
    subcategoryId: "sub-img-product",
    subcategoryName: "Creative",
    description: "Luxury artisanal jewelry maison e-commerce layout: 'Crafted Without Compromise', hand-forged oxidized silver ring showcase, and bespoke weight indicators.",
    promptText: "Editorial luxury jewelry maison lookbook and e-commerce experience named C*LA. Minimalist warm parchment background (#F5F3EF), high-fashion typography in serif and grotesque, clean editorial split columns '14–92g Per piece', 'Sterling & Silver', handcrafted oxidized rings on raw linen pedestal. Bespoke shopping bag drawer and tactile interactions.",
    safePreviewText: "Editorial luxury jewelry maison lookbook with handmade silver rings and parchment palette...",
    tags: ["Creative", "Landing Page", "Sections", "Recent", "Fintech", "Agency"],
    difficulty: "Beginner",
    style: "Haute Horlogerie Editorial",
    mood: "Artisanal & Minimalist",
    recommendedTools: [
      {
        toolId: "tool-midjourney",
        toolName: "Midjourney",
        modelName: "Midjourney v6.1",
        reason: "Stunning metal surface oxidation and macro jewelry highlights",
        badge: "Flagship Match",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Render Macro Pieces",
        instruction: "Generate high-detail product shots in Midjourney with --ar 4:5.",
      },
      {
        stepNumber: 2,
        title: "Deploy Editorial Layout",
        instruction: "Pair with clean serif typography and 14-92g weight metrics in your web storefront.",
      },
    ],
    thumbnailGradient: "from-stone-200 via-neutral-300 to-stone-400",
    likesCount: 19,
    savesCount: 14,
    isPublished: true,
    createdAt: "2026-03-06T09:00:00Z",
  },
  {
    id: "template-amber-editorial",
    name: "Amber Editorial",
    slug: "amber-editorial",
    categoryId: "cat-web-code",
    categoryName: "Agency",
    subcategoryId: "sub-web-saas",
    subcategoryName: "Agency",
    description: "Surreal terracotta-toned artistic studio landing page featuring cloudscapes, soaring white dove imagery, and a minimal Q&A accordion journal.",
    promptText: "Design an artistic agency and photography studio website in deep terracotta and amber clouds (#3d1c18 to #61271f). Floating white dove in flight, elegant centered navigation [Gallery] [Talents] [Journal] [Story], refined serif headline 'Q&A', poetic layout with soft grain overlay, fluid scroll reveal animations.",
    safePreviewText: "Artistic agency website with deep terracotta clouds, floating white dove, and Q&A accordion...",
    tags: ["Agency", "Creative", "Landing Page", "Sections", "Recent"],
    difficulty: "Intermediate",
    style: "Cinematic Warmth",
    mood: "Poetic & Evocative",
    recommendedTools: [
      {
        toolId: "tool-claude-code",
        toolName: "Claude Code",
        modelName: "Claude 3.7 Sonnet",
        reason: "Perfect artistic aesthetic layout and smooth typography tuning",
        badge: "Recommended",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Generate Poetic Layout",
        instruction: "Feed the prompt into your AI code builder for the warm terracotta cloud palette.",
      },
      {
        stepNumber: 2,
        title: "Animate Dove & Text",
        instruction: "Add floating CSS keyframes to the dove visual and serif accordion journal.",
      },
    ],
    thumbnailGradient: "from-red-950 via-amber-950 to-orange-950",
    likesCount: 23,
    savesCount: 17,
    isPublished: true,
    createdAt: "2026-03-06T08:00:00Z",
  },
  {
    id: "template-agent-wave",
    name: "Agent Wave",
    slug: "agent-wave",
    categoryId: "cat-web-code",
    categoryName: "Ai",
    subcategoryId: "sub-web-saas",
    subcategoryName: "Ai",
    description: "Sleek monochromatic AI agent orchestration platform with dynamic wave ribbon simulation: 'Train AI agents on your workflows in minutes.'",
    promptText: "Modern AI agent automation SaaS landing page named Agent Wave. Charcoal black background with smooth flowing 3D ribbon mesh in grayscale, bold headline 'Train AI agents on your workflows in minutes.', dual call-to-action buttons [Start Free Trial] and [Watch Interactive Demo], live terminal execution preview, built with Tailwind CSS and Next.js.",
    safePreviewText: "AI agent workflow platform with flowing 3D ribbon mesh and live terminal preview...",
    tags: ["Ai", "Saas", "Landing Page", "Technology", "Apps", "Hero"],
    difficulty: "Beginner",
    style: "Monochrome Minimalist 3D",
    mood: "Clean & High-Velocity",
    recommendedTools: [
      {
        toolId: "tool-lovable",
        toolName: "Lovable",
        modelName: "Lovable Fullstack",
        reason: "Rapid generation of terminal simulation and dark monochromatic styling",
        badge: "Flagship Match",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Initialize in Builder",
        instruction: "Paste prompt into Lovable or Bolt to generate the monochromatic SaaS hero.",
      },
      {
        stepNumber: 2,
        title: "Configure Agent Workflow",
        instruction: "Customize the interactive code terminal tabs for workflow automation steps.",
      },
    ],
    thumbnailGradient: "from-zinc-950 via-neutral-900 to-stone-900",
    likesCount: 31,
    savesCount: 24,
    isPublished: true,
    createdAt: "2026-03-06T07:00:00Z",
  },
  {
    id: "template-subway-sanctuary",
    name: "Subway Sanctuary",
    slug: "subway-sanctuary",
    categoryId: "cat-web-code",
    categoryName: "Creative",
    subcategoryId: "sub-web-portfolio",
    subcategoryName: "Creative",
    description: "Botanical immersive experiential landing page: an overgrown vintage subway carriage filled with wild wildflowers, moss, and warm yellow doors.",
    promptText: "Surreal botanical experience site for an urban re-wilding studio. High-detail photorealistic vintage yellow subway carriage interior transformed into an indoor wildflower sanctuary with ferns, daisies, and ivy vines crawling over stainless poles. Floating minimal menu [HOME] [ABOUT] [PORTFOLIO] [VISIT], interactive soundscape toggle, ambient sunlight rays through carriage windows.",
    safePreviewText: "Surreal botanical overgrown yellow subway carriage website with blooming wildflowers...",
    tags: ["Creative", "Portfolio", "Travel", "Wellness", "Recent"],
    difficulty: "Intermediate",
    style: "Biophilic Surrealism",
    mood: "Dreamy & Tranquil",
    recommendedTools: [
      {
        toolId: "tool-midjourney",
        toolName: "Midjourney",
        modelName: "Midjourney v6.1",
        reason: "Rich botanical textures, dappled lighting, and subway car realism",
        badge: "Flagship Match",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Render Sanctuary Visual",
        instruction: "Use Midjourney with prompt to create high-resolution overgrown carriage image.",
      },
      {
        stepNumber: 2,
        title: "Overlay Floating Menu",
        instruction: "Place floating transparent navigation header [HOME] [ABOUT] [PORTFOLIO] [VISIT].",
      },
    ],
    thumbnailGradient: "from-emerald-950 via-yellow-950 to-stone-900",
    likesCount: 26,
    savesCount: 22,
    isPublished: true,
    createdAt: "2026-03-06T06:00:00Z",
  },
  {
    id: "template-finpulse-global",
    name: "FinPulse Global",
    slug: "finpulse-global",
    categoryId: "cat-web-code",
    categoryName: "Fintech",
    subcategoryId: "sub-web-saas",
    subcategoryName: "Fintech",
    description: "Next-gen corporate treasury and multi-currency routing platform with real-time liquidity heatmaps and biometric security flows.",
    promptText: "High-yield institutional fintech dashboard and marketing page named FinPulse. Deep slate theme with emerald liquidity telemetry curves, multi-currency conversion ticker, secure biometric payout flows, enterprise-grade typography, compliant with open banking standards.",
    safePreviewText: "Fintech corporate treasury platform with liquidity telemetry curves and multi-currency ticker...",
    tags: ["Fintech", "Saas", "Technology", "Landing Page", "Apps"],
    difficulty: "Advanced",
    style: "Neo-Institutional FinTech",
    mood: "Trustworthy & Precise",
    recommendedTools: [
      {
        toolId: "tool-cursor",
        toolName: "Cursor",
        modelName: "Claude 3.7 Sonnet",
        reason: "Precision financial charts, dark mode UI, and enterprise security flows",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Setup Dashboard Layout",
        instruction: "Generate multi-currency tickers and emerald sparklines in Tailwind.",
      },
    ],
    thumbnailGradient: "from-slate-950 via-emerald-950 to-teal-950",
    likesCount: 38,
    savesCount: 30,
    isPublished: true,
    createdAt: "2026-03-06T05:00:00Z",
  },
  {
    id: "template-nomad-luxe",
    name: "Nomad Luxe Travel",
    slug: "nomad-luxe",
    categoryId: "cat-web-code",
    categoryName: "Travel",
    subcategoryId: "sub-web-saas",
    subcategoryName: "Travel",
    description: "Curated boutique travel club for remote founders featuring private Nordic villas, private flight charters, and wellness retreats.",
    promptText: "Ultra-luxury experiential travel club landing page. Full-bleed editorial photography of Scandinavian fjord retreat with outdoor thermal bath, custom serif headings, date picker with flight routing, member concierge drawer.",
    safePreviewText: "Luxury travel club landing page with Scandinavian fjord retreat and concierge booking...",
    tags: ["Travel", "Wellness", "Creative", "Landing Page"],
    difficulty: "Beginner",
    style: "Nordic Minimalist Luxury",
    mood: "Serene & Exclusive",
    recommendedTools: [
      {
        toolId: "tool-bolt",
        toolName: "Bolt.new",
        modelName: "Bolt WebContainer",
        reason: "Fluid booking modal drawers and interactive calendar pickers",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Deploy Booking Experience",
        instruction: "Scaffold member concierge and retreat dates with full-bleed imagery.",
      },
    ],
    thumbnailGradient: "from-cyan-950 via-blue-950 to-indigo-950",
    likesCount: 45,
    savesCount: 33,
    isPublished: true,
    createdAt: "2026-03-06T04:00:00Z",
  },
  {
    id: "template-aura-mind",
    name: "Aura Mind Wellness",
    slug: "aura-mind",
    categoryId: "cat-web-code",
    categoryName: "Wellness",
    subcategoryId: "sub-web-saas",
    subcategoryName: "Wellness",
    description: "Circadian mindfulness & sleep companion app landing page with soft organic ambient gradients and binaural frequency selector.",
    promptText: "Mindfulness and mental wellness web application named Aura. Gentle frosted glass cards with pastel sunset hues (lavender, peach, sky blue), soundwave visualizer for 432Hz sleep frequencies, daily check-in radial slider, breathing pacing orb animation.",
    safePreviewText: "Mindfulness and circadian sleep app with pastel sunset gradients and binaural frequencies...",
    tags: ["Wellness", "Apps", "Creative", "Sections"],
    difficulty: "Beginner",
    style: "Pastel Glass & Organic",
    mood: "Calming & Meditative",
    recommendedTools: [
      {
        toolId: "tool-lovable",
        toolName: "Lovable",
        modelName: "Lovable Fullstack",
        reason: "Soft pastel gradients and canvas soundwave frequency visualizer",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Implement Audio Player",
        instruction: "Render 432Hz sleep soundwaves with pulsing orb breathing pacing guide.",
      },
    ],
    thumbnailGradient: "from-purple-950 via-rose-950 to-amber-950",
    likesCount: 52,
    savesCount: 41,
    isPublished: true,
    createdAt: "2026-03-06T03:00:00Z",
  },
  {
    id: "template-vanguard-agency",
    name: "Vanguard Design Guild — Interactive Studio",
    slug: "vanguard-design-guild",
    categoryId: "cat-web-code",
    categoryName: "Agency",
    subcategoryId: "sub-web-saas",
    subcategoryName: "Agency",
    description: "Award-winning brutalist digital design agency portfolio with dynamic magnetic cursor interaction, split-screen case study reveals, and kinetic typography.",
    promptText: "Design a cutting-edge digital agency portfolio named Vanguard Design Guild. High-contrast monochrome theme with fluorescent electric lime accents (#ccff00). Kinetic typography with variable font weight distortion on scroll, interactive magnetic cursor following mouse trails, split-screen video case study drawer, responsive Tailwind CSS with framer-motion physics.",
    safePreviewText: "High-contrast digital agency portfolio with kinetic typography and electric lime accents...",
    tags: ["Agency", "Sections", "Hero", "Creative", "Portfolio", "Recent"],
    difficulty: "Intermediate",
    style: "Kinetic Brutalism",
    mood: "Bold & Avant-Garde",
    recommendedTools: [
      {
        toolId: "tool-cursor",
        toolName: "Cursor",
        modelName: "Claude 3.7 Sonnet",
        reason: "Best for framer-motion magnetic physics and custom cursor state",
        badge: "Flagship Match",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Initialize Studio Shell",
        instruction: "Drop prompt into Cursor to generate the brutalist layout with electric lime badges.",
      },
      {
        stepNumber: 2,
        title: "Configure Case Studies",
        instruction: "Link portfolio client showcases and client testimonials into the interactive drawer.",
      },
    ],
    thumbnailGradient: "from-zinc-950 via-neutral-900 to-lime-950",
    likesCount: 37,
    savesCount: 25,
    isPublished: true,
    createdAt: "2026-03-07T14:00:00Z",
  },
  {
    id: "template-monolith-agency",
    name: "Monolith Brand Architecture & Strategy",
    slug: "monolith-brand-architecture",
    categoryId: "cat-web-code",
    categoryName: "Agency",
    subcategoryId: "sub-web-saas",
    subcategoryName: "Agency",
    description: "Ultra-clean Scandinavian brand design agency website featuring monochrome bento project cards, case-study audio commentary toggle, and client roster carousel.",
    promptText: "Design an architectural brand consultancy website named Monolith. Deep obsidian slate palette (#0c0e12) with crisp Swiss typography in Helvetica Neue / Inter. Bento grid showing brand identity systems, audio commentary toggle for creative director notes, logo ticker carousel, subtle parallax scroll animations in Next.js and Tailwind.",
    safePreviewText: "Scandinavian brand consultancy website with dark Bento grid and Swiss typography...",
    tags: ["Agency", "Creative", "Landing Page", "Sections", "Recent"],
    difficulty: "Beginner",
    style: "Architectural Swiss Minimal",
    mood: "Prestigious & Authoritative",
    recommendedTools: [
      {
        toolId: "tool-lovable",
        toolName: "Lovable",
        modelName: "Lovable Fullstack",
        reason: "Rapid scaffolding of Scandinavian Bento grid and clean typography",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Deploy Agency Hero",
        instruction: "Use prompt in Lovable or Bolt to create the architectural layout.",
      },
    ],
    thumbnailGradient: "from-slate-950 via-zinc-900 to-stone-900",
    likesCount: 41,
    savesCount: 32,
    isPublished: true,
    createdAt: "2026-03-07T13:00:00Z",
  },
  {
    id: "template-kyoto-ryokan-travel",
    name: "Kyoto Ryokan Sanctuary — Zen Hideaway",
    slug: "kyoto-ryokan-sanctuary",
    categoryId: "cat-web-code",
    categoryName: "Travel",
    subcategoryId: "sub-web-portfolio",
    subcategoryName: "Travel",
    description: "Serene traditional Japanese ryokan retreat booking portal with bamboo grove ambient audio, cedar bath reservation drawer, and seasonal Kaiseki dining menu.",
    promptText: "Create a tranquil luxury Japanese ryokan boutique hotel website named Kyoto Sanctuary. Dark Hinoki cedar and sumi ink palette (#181716), delicate vertical Japanese kanji accent characters, date selector for private onsen suites, ambient background soundscape toggle (rain & bamboo flute), smooth fade transitions.",
    safePreviewText: "Traditional luxury Japanese ryokan hotel website with Hinoki cedar tones and onsen booking...",
    tags: ["Travel", "Wellness", "Creative", "Landing Page", "Recent"],
    difficulty: "Intermediate",
    style: "Wabi-Sabi Minimalist",
    mood: "Peaceful & Immersive",
    recommendedTools: [
      {
        toolId: "tool-midjourney",
        toolName: "Midjourney",
        modelName: "Midjourney v6.1",
        reason: "Photorealistic traditional Japanese garden courtyards and steam mist",
        badge: "Flagship Match",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Render Atmosphere",
        instruction: "Generate serene mist-shrouded cedar bath visuals with Midjourney.",
      },
      {
        stepNumber: 2,
        title: "Configure Suite Booking",
        instruction: "Implement onsen availability drawer and Kaiseki dining schedule.",
      },
    ],
    thumbnailGradient: "from-stone-950 via-stone-900 to-amber-950",
    likesCount: 49,
    savesCount: 36,
    isPublished: true,
    createdAt: "2026-03-07T12:00:00Z",
  },
  {
    id: "template-alpine-expedition-travel",
    name: "Alpine Expedition Club — High-Altitude Lodges",
    slug: "alpine-expedition-club",
    categoryId: "cat-web-code",
    categoryName: "Travel",
    subcategoryId: "sub-web-saas",
    subcategoryName: "Travel",
    description: "Luxury Swiss mountain lodge and private helicopter ski club portal with live weather telemetry, topographical 3D peak map, and gear checklist.",
    promptText: "Design a high-altitude expedition travel club web experience named Alpine Club. Glacial navy and frost white aesthetic, interactive 3D contour peak topography, live avalanche & weather sensor bar, gear checkout drawer, booking flow for private Zermatt chalets.",
    safePreviewText: "High-altitude mountain expedition club website with 3D contour topography and weather sensors...",
    tags: ["Travel", "Apps", "Hero", "Creative", "Recent"],
    difficulty: "Intermediate",
    style: "Editorial Mountain Luxury",
    mood: "Adventurous & High-Altitude",
    recommendedTools: [
      {
        toolId: "tool-bolt",
        toolName: "Bolt.new",
        modelName: "Bolt WebContainer",
        reason: "Interactive weather widgets and topographical canvas maps",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Build Alpine Portal",
        instruction: "Use Bolt to build weather sensors and chalet reservation calendar.",
      },
    ],
    thumbnailGradient: "from-slate-950 via-blue-950 to-cyan-950",
    likesCount: 33,
    savesCount: 28,
    isPublished: true,
    createdAt: "2026-03-07T11:00:00Z",
  },
  {
    id: "template-solaria-crypto-fintech",
    name: "Solaria Institutional Yield & Staking Vaults",
    slug: "solaria-institutional-yield",
    categoryId: "cat-web-code",
    categoryName: "Fintech",
    subcategoryId: "sub-web-saas",
    subcategoryName: "Fintech",
    description: "Decentralized automated liquidity aggregator and real-time yield optimizer dashboard featuring dark obsidian theme, live candlestick charts, and multi-chain bridging.",
    promptText: "Design an institutional DeFi staking and automated liquidity vault dashboard named Solaria. Pitch black background (#060608) with luminous emerald & cyan glowing telemetry graphs. Real-time APY ticker, slippage tolerance selector, multi-chain gas fee estimator, biometric ledger signing modal, built in Tailwind and React.",
    safePreviewText: "Institutional DeFi staking vault dashboard with real-time APY telemetry and candlestick charts...",
    tags: ["Fintech", "Technology", "Apps", "Saas", "Hero", "Recent"],
    difficulty: "Advanced",
    style: "Cyber Glassmorphism",
    mood: "High-Frequency & Secure",
    recommendedTools: [
      {
        toolId: "tool-cursor",
        toolName: "Cursor",
        modelName: "Claude 3.7 Sonnet",
        reason: "Complex multi-chain state, web3 wallet connector, and responsive charts",
        badge: "Flagship Match",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Generate Trading Dashboard",
        instruction: "Paste prompt into Cursor to scaffold the dark obsidian staking interface.",
      },
    ],
    thumbnailGradient: "from-zinc-950 via-emerald-950 to-teal-950",
    likesCount: 56,
    savesCount: 44,
    isPublished: true,
    createdAt: "2026-03-07T10:00:00Z",
  },
  {
    id: "template-aether-card-fintech",
    name: "Aether Black Titanium Corporate Card",
    slug: "aether-black-titanium-card",
    categoryId: "cat-web-code",
    categoryName: "Fintech",
    subcategoryId: "sub-web-saas",
    subcategoryName: "Fintech",
    description: "High-net-worth commercial smart card experience with 3D metallic card tilt physics, automated spend governance, and zero-FX international settlement.",
    promptText: "Design a luxury corporate card landing experience named Aether Titanium. Centered 3D brushed black titanium card with gyroscope mouse-tilt shine, dynamic spend limit slider ($50,000 - $1,000,000), luxury minimalist typography, instant digital Apple Wallet issuance simulator.",
    safePreviewText: "Commercial corporate titanium card experience with 3D mouse tilt shine and spend governance...",
    tags: ["Fintech", "Landing Page", "Hero", "Saas", "Sections", "Recent"],
    difficulty: "Intermediate",
    style: "Obsidian Titanium Luxury",
    mood: "Elite & Seamless",
    recommendedTools: [
      {
        toolId: "tool-lovable",
        toolName: "Lovable",
        modelName: "Lovable Fullstack",
        reason: "Seamless CSS 3D perspective card tilt and real-time sliders",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Scaffold Card Experience",
        instruction: "Use prompt in Lovable to build the mouse-tracking titanium card shine.",
      },
    ],
    thumbnailGradient: "from-neutral-950 via-slate-900 to-zinc-900",
    likesCount: 47,
    savesCount: 39,
    isPublished: true,
    createdAt: "2026-03-07T09:00:00Z",
  },
  {
    id: "template-soma-breathwork-wellness",
    name: "Soma Somatic Breathwork & Vagus Nerve Pacer",
    slug: "soma-somatic-breathwork",
    categoryId: "cat-web-code",
    categoryName: "Wellness",
    subcategoryId: "sub-web-saas",
    subcategoryName: "Wellness",
    description: "Interactive physiological resonance trainer with fluid expanding orb animation, binaural 40Hz gamma pulses, and HRV biofeedback telemetry.",
    promptText: "Design a somatic nervous system regulation and box-breathing web app named Soma. Ethereal twilight aura gradients (deep violet, rose quartz, celestial cyan), smooth pulsing inhalation-hold-exhalation animation cycle with seconds countdown, soothing frequency audio toggle (528Hz love tone), HRV telemetry dashboard.",
    safePreviewText: "Somatic breathwork pacer with ethereal twilight gradients and pulsing breathing orb...",
    tags: ["Wellness", "Apps", "Creative", "Sections", "Hero", "Recent"],
    difficulty: "Beginner",
    style: "Organic Radiant Aurora",
    mood: "Restorative & Transcendental",
    recommendedTools: [
      {
        toolId: "tool-lovable",
        toolName: "Lovable",
        modelName: "Lovable Fullstack",
        reason: "Smooth SVG pulse keyframes and Web Audio API tone generator",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Initialize Breath Pacer",
        instruction: "Feed prompt to Lovable to render the expanding breathing orb.",
      },
    ],
    thumbnailGradient: "from-indigo-950 via-purple-950 to-rose-950",
    likesCount: 63,
    savesCount: 51,
    isPublished: true,
    createdAt: "2026-03-07T08:00:00Z",
  },
  // ----------------------------------------------------
  // IMAGE GENERATION (Flagship & deep scenario)
  // ----------------------------------------------------
  {
    id: "template-candle-photo",
    name: "Product Photography — Handmade Candle",
    slug: "product-photography-handmade-candle",
    categoryId: "cat-image-gen",
    categoryName: "Image Generation",
    subcategoryId: "sub-img-product",
    subcategoryName: "Product Photography",
    description: "A clean, photorealistic product photograph of a handmade scented soy candle on a raw limestone pedestal, surrounded by botanical eucalyptus twigs and soft morning window light.",
    promptText: "Commercial editorial product photograph of a minimalist handmade soy candle in an amber glass jar with a minimalist matte cream label, resting on a rough-hewn travertine stone pedestal. Soft diffused morning sunlight streaming through a linen curtain casting delicate window shadows, single dried eucalyptus twig beside the jar, shallow depth of field, warm golden ambient tones, 85mm lens, f/2.8, shot on Hasselblad H6D-100c, award-winning studio lighting --ar 4:5 --v 6.1 --style raw",
    safePreviewText: "Commercial editorial product photograph of a minimalist handmade soy candle in an amber glass jar...",
    tags: ["Product", "Studio", "Commercial", "Lighting", "E-Commerce", "Warm"],
    difficulty: "Beginner",
    style: "Editorial Studio",
    mood: "Warm & Organic",
    recommendedTools: [
      {
        toolId: "tool-midjourney",
        toolName: "Midjourney",
        modelName: "Midjourney v6.1",
        reason: "Best for photorealistic studio lighting and warm waxy textures",
        badge: "Flagship Match",
      },
      {
        toolId: "tool-flux",
        toolName: "Flux",
        modelName: "FLUX.1 Schnell",
        reason: "Excellent label typography rendering and crisp edge sharpness",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Access Prompt Command",
        instruction: "Open Midjourney on Discord or Web and initiate the `/imagine` prompt command.",
      },
      {
        stepNumber: 2,
        title: "Paste Verbatim",
        instruction: "Paste the copied prompt from AWA directly into the prompt box without altering parameters.",
      },
      {
        stepNumber: 3,
        title: "Retain Aspect Ratio",
        instruction: "Ensure the `--ar 4:5` flag remains at the end to match standard online shop product grids.",
      },
      {
        stepNumber: 4,
        title: "Review 4-Grid Output",
        instruction: "Review the initial 4 variations. Pick variation 1 or 2 for the sharpest label typography.",
      },
      {
        stepNumber: 5,
        title: "Upscale & Export",
        instruction: "Click 'Upscale' on your preferred variation to get the high-resolution 2048x2560 export for your shop.",
      },
    ],
    videoUrl: "https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ",
    thumbnailGradient: "from-amber-600 via-orange-700 to-stone-900",
    likesCount: 1420,
    savesCount: 890,
    isPublished: true,
    createdAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "template-luxury-watch",
    name: "Luxury Chronograph Watch on Dark Carbon",
    slug: "luxury-chronograph-watch-carbon",
    categoryId: "cat-image-gen",
    categoryName: "Image Generation",
    subcategoryId: "sub-img-product",
    subcategoryName: "Product Photography",
    description: "Ultra-crisp horology advertisement of a stainless steel chronograph timepiece on brushed carbon fiber with rim lighting.",
    promptText: "High-end luxury Swiss chronograph wristwatch in brushed stainless steel with sapphire crystal face and emerald green dial, macro detail shot resting on angled forged carbon fiber. Subtle blue rim lighting along bezel edge, razor sharp reflections on beveled casing, studio softbox illumination, 100mm macro lens f/4, crisp tachymeter markings, 8k resolution commercial print aesthetic --ar 1:1 --v 6.1",
    safePreviewText: "High-end luxury Swiss chronograph wristwatch in brushed stainless steel with sapphire crystal face...",
    tags: ["Watches", "Luxury", "Macro", "Dark Mode", "Commercial"],
    difficulty: "Intermediate",
    style: "High Contrast Commercial",
    mood: "Sleek & Prestigious",
    recommendedTools: [
      {
        toolId: "tool-midjourney",
        toolName: "Midjourney",
        modelName: "Midjourney v6.1",
        reason: "Precision metallic specular highlights and clean crystal refractions",
        badge: "Recommended",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Open Midjourney",
        instruction: "Navigate to Midjourney `/imagine` prompt dialog.",
      },
      {
        stepNumber: 2,
        title: "Submit Prompt",
        instruction: "Paste prompt exactly to preserve macro lens and carbon fiber texture details.",
      },
      {
        stepNumber: 3,
        title: "Select Cleanest Dial",
        instruction: "Check hands alignment and tachymeter numbers before choosing your final upscale.",
      },
      {
        stepNumber: 4,
        title: "Subtle Vary if Needed",
        instruction: "Use 'Vary (Subtle)' if you wish to adjust glint position across the bezel.",
      },
    ],
    thumbnailGradient: "from-slate-800 via-emerald-950 to-neutral-950",
    likesCount: 980,
    savesCount: 650,
    isPublished: true,
    createdAt: "2026-03-02T11:30:00Z",
  },
  {
    id: "template-cyberpunk-portrait",
    name: "Cyberpunk Rain-Drenched Alleyway Portrait",
    slug: "cyberpunk-rain-alleyway-portrait",
    categoryId: "cat-image-gen",
    categoryName: "Image Generation",
    subcategoryId: "sub-img-portraits",
    subcategoryName: "Portraits & Characters",
    description: "Atmospheric street portrait of a cyberpunk character wearing a transparent raincoat with neon reflections on wet asphalt.",
    promptText: "Cinematic medium close-up portrait of an East Asian woman with futuristic cybernetic brow implants, wearing an iridescent transparent vinyl trench coat over streetwear. Wet neon-soaked alleyway in neo-Tokyo with magenta and teal holographic signs reflected on puddle surfaces, heavy raindrops caught in mid-air, 35mm film grain, anamorphic lens flare, moody color grading --ar 16:9 --v 6.1 --style raw",
    safePreviewText: "Cinematic medium close-up portrait of an East Asian woman with futuristic cybernetic brow implants...",
    tags: ["Cyberpunk", "Portrait", "Neon", "Cinematic", "Night"],
    difficulty: "Beginner",
    style: "Neo-Noir",
    mood: "Moody & Electric",
    recommendedTools: [
      {
        toolId: "tool-midjourney",
        toolName: "Midjourney",
        modelName: "Midjourney v6.1",
        reason: "Exceptional skin texture, wet specular reflections, and chromatic depth",
        badge: "Best Match",
      },
      {
        toolId: "tool-sdxl",
        toolName: "Stable Diffusion",
        modelName: "SDXL 1.0",
        reason: "Great control over custom neon LoRA weights",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Input Prompt",
        instruction: "Run prompt in Midjourney with 16:9 cinematic ratio intact.",
      },
      {
        stepNumber: 2,
        title: "Evaluate Rain Particles",
        instruction: "Inspect the reflection quality on the transparent vinyl jacket.",
      },
      {
        stepNumber: 3,
        title: "Upscale",
        instruction: "Pick the image with the most balanced teal and magenta backlight harmony.",
      },
    ],
    thumbnailGradient: "from-fuchsia-900 via-purple-900 to-cyan-950",
    likesCount: 1120,
    savesCount: 790,
    isPublished: true,
    createdAt: "2026-03-04T14:00:00Z",
  },
  {
    id: "template-nordic-interior",
    name: "Nordic Architectural Living Room at Dusk",
    slug: "nordic-architectural-living-room-dusk",
    categoryId: "cat-image-gen",
    categoryName: "Image Generation",
    subcategoryId: "sub-img-architecture",
    subcategoryName: "Architecture & Interiors",
    description: "Expansive modern Scandinavian living room with floor-to-ceiling glass, concrete walls, warm fire pit, and snowy pine view.",
    promptText: "Architectural interior photography of a minimalist Scandinavian open-plan living pavilion at twilight. Cast concrete wall, low-slung oak lounge chairs, sunken conversation pit with a linear gas fire, double-height floor-to-ceiling glass wall looking out over snow-covered Swedish pine forest. Warm interior recessed 2700K lighting contrasting with deep blue twilight exterior, architectural digest editorial --ar 16:9 --v 6.1",
    safePreviewText: "Architectural interior photography of a minimalist Scandinavian open-plan living pavilion...",
    tags: ["Architecture", "Interior", "Minimalist", "Cozy", "Scandinavian"],
    difficulty: "Beginner",
    style: "Architectural Digest",
    mood: "Serene & Sophisticated",
    recommendedTools: [
      {
        toolId: "tool-midjourney",
        toolName: "Midjourney",
        modelName: "Midjourney v6.1",
        reason: "Realistic wood grains, balanced exposure between interior warm lights and dusk exterior",
        badge: "Top Choice",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Run Imagine",
        instruction: "Paste prompt into Midjourney with `--ar 16:9` ratio for architectural framing.",
      },
      {
        stepNumber: 2,
        title: "Check Perspective",
        instruction: "Look for straight vertical perspective lines along structural window mullions.",
      },
      {
        stepNumber: 3,
        title: "Upscale",
        instruction: "Export the render that produces the softest glow around the sunken fireplace.",
      },
    ],
    thumbnailGradient: "from-slate-700 via-stone-800 to-indigo-950",
    likesCount: 840,
    savesCount: 620,
    isPublished: true,
    createdAt: "2026-03-05T09:15:00Z",
  },

  // ----------------------------------------------------
  // VIDEO GENERATION
  // ----------------------------------------------------
  {
    id: "template-video-drone-mountains",
    name: "Cinematic Misty Mountain Drone Sweep",
    slug: "cinematic-misty-mountain-drone-sweep",
    categoryId: "cat-video-gen",
    categoryName: "Video Generation",
    subcategoryId: "sub-vid-cinematic",
    subcategoryName: "Cinematic & B-Roll",
    description: "Smooth 4K FPV drone dive through morning clouds over jagged alpine mountain peaks with golden hour rays.",
    promptText: "Cinematic aerial FPV drone footage gliding smoothly forwards over dramatic snow-dusted jagged mountain ridges in the Dolomites. Layered valley mist gently swirling below, warm golden sunrise breaking through cloud breaks creating dramatic volumetric god rays. Ultra-stable cinematic gimbal motion, natural motion blur, slow 24fps motion, 4k resolution, National Geographic documentary style",
    safePreviewText: "Cinematic aerial FPV drone footage gliding smoothly forwards over dramatic snow-dusted jagged mountain ridges...",
    tags: ["Aerial", "Landscape", "Drone", "Cinematic", "Mountains", "Nature"],
    difficulty: "Beginner",
    style: "Documentary Film",
    mood: "Epic & Majestic",
    recommendedTools: [
      {
        toolId: "tool-runway",
        toolName: "Runway",
        modelName: "Runway Gen-3 Alpha",
        reason: "Highest temporal coherence and natural cloud-mist volumetric motion",
        badge: "Best for Video",
      },
      {
        toolId: "tool-sora",
        toolName: "OpenAI Sora",
        modelName: "Sora 1.0 (Direct API)",
        reason: "Unmatched scale and physical accuracy over extended 10s video generations",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Open Runway Gen-3",
        instruction: "Log in to RunwayML dashboard and select 'Text to Video' Gen-3 Alpha model.",
      },
      {
        stepNumber: 2,
        title: "Paste Camera Prompt",
        instruction: "Paste prompt into the text prompt field; do not overload with negative prompts.",
      },
      {
        stepNumber: 3,
        title: "Set Camera Direction",
        instruction: "Set Motion intensity to 3 and select Camera 'Forward Pan' for silky forward gliding.",
      },
      {
        stepNumber: 4,
        title: "Generate 5s/10s Clip",
        instruction: "Generate initial 5s preview, then use 'Extend' if longer B-roll sequence is needed.",
      },
    ],
    thumbnailGradient: "from-indigo-900 via-sky-800 to-amber-700",
    likesCount: 1650,
    savesCount: 1240,
    isPublished: true,
    createdAt: "2026-03-02T15:20:00Z",
  },
  {
    id: "template-video-slowmo-coffee",
    name: "Slow Motion Espresso Extraction Pour",
    slug: "slow-motion-espresso-extraction",
    categoryId: "cat-video-gen",
    categoryName: "Video Generation",
    subcategoryId: "sub-vid-commercial",
    subcategoryName: "Commercial & Product Motion",
    description: "Ultra-macro 120fps high-speed capture of rich tiger-striped espresso crema pouring into a clear double-walled glass cup.",
    promptText: "Macro high-speed slow motion video at 120fps of rich caramel-toned espresso pouring from a bottomless portafilter into a crystal-clear glass cup. Viscous crema creating delicate tiger stripes and micro-droplets dancing in mid-air, subtle backlit steam curling upwards, shallow depth of field, warm artisanal cafe atmosphere, luxury food commercial aesthetic",
    safePreviewText: "Macro high-speed slow motion video at 120fps of rich caramel-toned espresso pouring...",
    tags: ["Coffee", "Slow Motion", "Macro", "Commercial", "Food"],
    difficulty: "Intermediate",
    style: "Macro High-Speed",
    mood: "Indulgent & Warm",
    recommendedTools: [
      {
        toolId: "tool-runway",
        toolName: "Runway",
        modelName: "Runway Gen-3 Alpha Turbo",
        reason: "Rapid iteration for liquid viscosity dynamics without fluid tearing",
        badge: "Recommended",
      },
      {
        toolId: "tool-pika",
        toolName: "Pika",
        modelName: "Pika 1.5",
        reason: "Specialized physics engine handles liquid drip expansions well",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Configure Video Length",
        instruction: "Select 5-second duration in Runway or Pika.",
      },
      {
        stepNumber: 2,
        title: "Paste Prompt",
        instruction: "Keep the words 'viscous crema' and '120fps' as they trigger fluid deceleration.",
      },
      {
        stepNumber: 3,
        title: "Export MP4",
        instruction: "Download at 1080p and apply subtle contrast grading in your editor.",
      },
    ],
    thumbnailGradient: "from-amber-950 via-amber-800 to-stone-900",
    likesCount: 780,
    savesCount: 510,
    isPublished: true,
    createdAt: "2026-03-06T12:00:00Z",
  },
  {
    id: "template-video-fashion-walk",
    name: "Futuristic Hologram Jacket Runway Walk",
    slug: "futuristic-hologram-jacket-runway",
    categoryId: "cat-video-gen",
    categoryName: "Video Generation",
    subcategoryId: "sub-vid-fashion",
    subcategoryName: "Fashion & Pacing",
    description: "High-fashion model walking in slow motion down an infinite mirrored runway, jacket shifting through iridescent prism colors.",
    promptText: "Avant-garde fashion runway video tracking backwards in slow motion. High fashion model with sleek slicked-back hair strides forward confidently down an infinite mirrored runway. Their oversized sculptural coat shifts fluidly between chromatic silver and iridescent prism violet waves with every step, strobe lights pulsing softly in the dark void background, high-contrast editorial catwalk cinematography",
    safePreviewText: "Avant-garde fashion runway video tracking backwards in slow motion. High fashion model strides forward...",
    tags: ["Fashion", "Holographic", "Runway", "Slow Motion", "Editorial"],
    difficulty: "Intermediate",
    style: "Avant-Garde Catwalk",
    mood: "Hypnotic & Futuristic",
    recommendedTools: [
      {
        toolId: "tool-runway",
        toolName: "Runway",
        modelName: "Runway Gen-3 Alpha",
        reason: "Smooth cloth deformation physics and tracking camera motion",
        badge: "Top Choice",
      },
      {
        toolId: "tool-pika",
        toolName: "Pika",
        modelName: "Pika 1.5",
        reason: "Dynamic motion brush enables localized iridescent pulses",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Select Tracking Shot",
        instruction: "Choose 'Reverse tracking' or backward camera motion in tool settings.",
      },
      {
        stepNumber: 2,
        title: "Input Prompt",
        instruction: "Paste prompt directly. Ensure motion parameter is set around 4 for elegant walking cadence.",
      },
      {
        stepNumber: 3,
        title: "Review Strobe Timing",
        instruction: "Verify that model's face maintains consistency across all frames.",
      },
    ],
    thumbnailGradient: "from-purple-950 via-violet-900 to-fuchsia-950",
    likesCount: 890,
    savesCount: 680,
    isPublished: true,
    createdAt: "2026-03-07T16:40:00Z",
  },

  // ----------------------------------------------------
  // WEBSITE MAKING
  // ----------------------------------------------------
  {
    id: "template-web-saas-dark",
    name: "Dark Mode AI SaaS Landing Page with Pricing Matrix",
    slug: "dark-mode-ai-saas-landing-page",
    categoryId: "cat-website-making",
    categoryName: "Website Making",
    subcategoryId: "sub-web-saas",
    subcategoryName: "SaaS & Tech Landing Pages",
    description: "High-converting modern landing page prompt tailored for v0 and Framer, featuring glassmorphism cards, interactive pricing toggle, and animated glow borders.",
    promptText: "Build a modern, high-converting dark mode AI developer platform landing page in React, Next.js App Router, and Tailwind CSS with shadcn/ui components. Include: 1) A bold hero section with gradient badge 'v2.0 Just Released', headline 'Deploy Agentic AI in Minutes', subtext, dual CTA buttons ('Start Free Trial' and 'View Documentation'), and a floating interactive dashboard preview with subtle radial violet glow behind it. 2) Social proof bar with 6 monochrome client logos. 3) 3-column feature grid with glassmorphism card surfaces, Lucide icons, and subtle hover borders. 4) Annual vs Monthly toggle pricing table with 3 tiers (Starter, Pro [highlighted with popular badge], Enterprise). 5) Sticky glass navbar with logo, 4 links, and sign-in button. Responsive mobile layout with drawer navigation.",
    safePreviewText: "Build a modern, high-converting dark mode AI developer platform landing page in React, Next.js...",
    tags: ["SaaS", "Dark Mode", "Landing Page", "Tailwind", "React", "v0"],
    difficulty: "Beginner",
    style: "Modern Glassmorphism",
    mood: "High-Tech & Credible",
    recommendedTools: [
      {
        toolId: "tool-v0",
        toolName: "v0 by Vercel",
        modelName: "v0 React / Tailwind",
        reason: "Outputs immediate copy-pasteable clean TypeScript and Tailwind components",
        badge: "Best for v0",
      },
      {
        toolId: "tool-framer-ai",
        toolName: "Framer AI",
        modelName: "Framer AI 2.0",
        reason: "Transforms prompt into responsive no-code site with native animations in 30s",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Open v0.dev",
        instruction: "Navigate to v0.dev or create a new Framer AI project.",
      },
      {
        stepNumber: 2,
        title: "Paste Architecture Prompt",
        instruction: "Paste prompt into the generative chat box. Do not trim the 5 numbered sections.",
      },
      {
        stepNumber: 3,
        title: "Preview & Iterate",
        instruction: "Verify the pricing toggle interacts cleanly and mobile drawer collapses as expected.",
      },
      {
        stepNumber: 4,
        title: "Copy Code / Publish",
        instruction: "Click 'Copy Code' into your Next.js project or click 'Publish' inside Framer.",
      },
    ],
    thumbnailGradient: "from-slate-900 via-indigo-950 to-blue-900",
    likesCount: 2140,
    savesCount: 1680,
    isPublished: true,
    createdAt: "2026-03-01T08:00:00Z",
  },
  {
    id: "template-web-artisan-portfolio",
    name: "Artisan Ceramic Studio E-Commerce Showcase",
    slug: "artisan-ceramic-studio-ecommerce",
    categoryId: "cat-website-making",
    categoryName: "Website Making",
    subcategoryId: "sub-web-ecommerce",
    subcategoryName: "E-Commerce & Portfolios",
    description: "Earthy, minimalist portfolio and shop layout for an artisan ceramicist, featuring large image galleries and slide-out cart.",
    promptText: "Create a serene, high-end editorial website for a Kyoto-inspired artisan ceramics atelier. Style guidelines: warm oat-milk background (#F7F4EE), deep charcoal typography, serif headings (Playfair Display) paired with clean geometric sans body. Layout components: 1) Full-bleed hero banner with poetic craft statement and 'Explore Collection' button. 2) Staggered asymmetrical 2-column product grid showcasing handmade cups, vases, and bowls with price tags and quick-add affordance. 3) 'Behind the Clay' maker biography section with video placeholder and studio philosophy quote. 4) Slide-out cart drawer mockup and newsletter signup. Responsive, generous whitespace, warm luxury feel.",
    safePreviewText: "Create a serene, high-end editorial website for a Kyoto-inspired artisan ceramics atelier...",
    tags: ["E-Commerce", "Artisan", "Ceramics", "Minimalist", "Editorial"],
    difficulty: "Intermediate",
    style: "Wabi-Sabi Editorial",
    mood: "Peaceful & Tactile",
    recommendedTools: [
      {
        toolId: "tool-framer-ai",
        toolName: "Framer AI",
        modelName: "Framer AI 2.0",
        reason: "Effortlessly reproduces sophisticated asymmetrical image layouts and smooth scroll",
        badge: "Top Choice",
      },
      {
        toolId: "tool-v0",
        toolName: "v0 by Vercel",
        modelName: "v0 React / Tailwind",
        reason: "Creates modular React shopping cart state and product card components",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Start in Framer or v0",
        instruction: "Open a fresh generation canvas.",
      },
      {
        stepNumber: 2,
        title: "Submit Prompt",
        instruction: "Feed the detailed color codes and typography directives into the engine.",
      },
      {
        stepNumber: 3,
        title: "Customize Imagery",
        instruction: "Swap placeholder ceramics photos with your own actual product imagery.",
      },
    ],
    thumbnailGradient: "from-stone-300 via-amber-200 to-stone-400",
    likesCount: 940,
    savesCount: 710,
    isPublished: true,
    createdAt: "2026-03-03T10:20:00Z",
  },

  // ----------------------------------------------------
  // SLIDES & PRESENTATIONS
  // ----------------------------------------------------
  {
    id: "template-slides-seed-pitch",
    name: "10-Slide Seed Stage Venture Capital Pitch Deck",
    slug: "10-slide-seed-venture-pitch-deck",
    categoryId: "cat-slides-presentations",
    categoryName: "Slides & Presentations",
    subcategoryId: "sub-slides-pitch",
    subcategoryName: "Pitch Decks & Fundraising",
    description: "Battle-tested 10-slide venture capital pitch deck structure optimized for Gamma and Beautiful.ai, following the classic Sequoia narrative framework.",
    promptText: "Generate an institutional-grade 10-slide Seed stage fundraising presentation deck for an enterprise B2B workflow automation startup. Slide sequence: 1) Title Slide: Company name, one-line vision, presenter info. 2) The Problem: 3 quantified pain points of manual enterprise compliance. 3) The Solution: Our AI automation engine with a 3-step value diagram. 4) Why Now?: Regulatory shifts and LLM capability inflection. 5) Product & Architecture: Screen mockup with 3 core differentiators. 6) Market Size: TAM ($42B), SAM ($8.5B), SOM ($1.2B) visual concentric circles. 7) Traction & Metrics: 4 metric callout cards (MoM Growth, NRR, Pilot logos, CAC payback). 8) Business Model: Land and expand pricing tiers. 9) Team: 3 founders with ex-Google/Stripe pedigree. 10) The Ask: $3.5M Seed round allocation breakdown. Clean dark navy theme, high contrast metric typography, minimal bullet points.",
    safePreviewText: "Generate an institutional-grade 10-slide Seed stage fundraising presentation deck for an enterprise...",
    tags: ["Pitch Deck", "Venture Capital", "Fundraising", "Sequoia", "B2B", "Gamma"],
    difficulty: "Beginner",
    style: "Institutional VC",
    mood: "Confident & Data-Driven",
    recommendedTools: [
      {
        toolId: "tool-gamma",
        toolName: "Gamma",
        modelName: "Gamma Presentation AI",
        reason: "Automatically creates properly formatted stat cards, concentric market sizing diagrams, and slide pacing",
        badge: "Best for Decks",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Open Gamma App",
        instruction: "Sign in to Gamma.app and select 'New from AI' → 'Presentation'.",
      },
      {
        stepNumber: 2,
        title: "Paste Outline Prompt",
        instruction: "Paste the 10-slide structure verbatim into Gamma's generation prompt box.",
      },
      {
        stepNumber: 3,
        title: "Select 10 Cards",
        instruction: "Ensure Gamma generates exactly 10 distinct presentation cards.",
      },
      {
        stepNumber: 4,
        title: "Review Metrics",
        instruction: "Substitute placeholder figures with your actual founder team and revenue metrics.",
      },
    ],
    thumbnailGradient: "from-blue-950 via-slate-900 to-indigo-950",
    likesCount: 1890,
    savesCount: 1540,
    isPublished: true,
    createdAt: "2026-03-01T12:00:00Z",
  },
  {
    id: "template-slides-qbr",
    name: "Quarterly Business Review (QBR) Executive Briefing",
    slug: "qbr-executive-briefing",
    categoryId: "cat-slides-presentations",
    categoryName: "Slides & Presentations",
    subcategoryId: "sub-slides-corporate",
    subcategoryName: "Executive & QBR Briefings",
    description: "Polished executive slide structure for reporting quarterly revenue, OKR achievements, customer churn analysis, and next quarter bets.",
    promptText: "Create a 6-slide high-impact Quarterly Business Review (QBR) presentation deck for C-suite executive review. Visual theme: minimalist monochrome charcoal with emerald green accent highlights. Slides required: 1) Executive Summary: High-level OKR scorecards and revenue summary. 2) Revenue Performance: Bar charts comparing Q3 target vs actuals with YoY growth percentages. 3) Key Wins & Customer Case Study: Enterprise logo and 3 bulleted achievement highlights. 4) Challenges & Churn Diagnostics: Root cause analysis table with mitigation steps. 5) Product Roadmap Delivery: Timeline graphic showing shipped features vs delayed items. 6) Q4 Strategic Focus & Resource Allocation. Executive tone, clean tables, zero clutter.",
    safePreviewText: "Create a 6-slide high-impact Quarterly Business Review (QBR) presentation deck for C-suite...",
    tags: ["QBR", "Corporate", "Executive", "Analytics", "OKR"],
    difficulty: "Intermediate",
    style: "Executive Minimalist",
    mood: "Objective & Professional",
    recommendedTools: [
      {
        toolId: "tool-gamma",
        toolName: "Gamma",
        modelName: "Gamma Presentation AI",
        reason: "Formats tables and KPI scorecards with clear visual hierarchy",
        badge: "Recommended",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Run in Gamma",
        instruction: "Use Gamma's document-to-deck or prompt builder.",
      },
      {
        stepNumber: 2,
        title: "Fill Financial Data",
        instruction: "Update OKR scorecards and chart values to match your team's quarterly numbers.",
      },
    ],
    thumbnailGradient: "from-emerald-950 via-slate-900 to-neutral-900",
    likesCount: 650,
    savesCount: 490,
    isPublished: true,
    createdAt: "2026-03-05T14:30:00Z",
  },

  // ----------------------------------------------------
  // POSTER & DESIGN
  // ----------------------------------------------------
  {
    id: "template-poster-swiss-festival",
    name: "Electronic Music Festival Poster (Swiss Style)",
    slug: "electronic-music-festival-swiss-poster",
    categoryId: "cat-poster-design",
    categoryName: "Poster & Design",
    subcategoryId: "sub-poster-events",
    subcategoryName: "Music & Cultural Events",
    description: "Iconic International Typographic Style (Swiss Grid) poster featuring stark geometric abstractions, bold Akzidenz-Grotesk lettering, and duotone colors.",
    promptText: "Graphic design poster in the authentic International Typographic Style (Swiss Style, 1960s Josef Müller-Brockmann). Bold rigid modular mathematical grid layout, oversized black geometric circular soundwave abstraction dominating center, vibrant electric vermillion red and cream paper duotone color scheme. Ultra-clean typography hierarchy with festival dates, Tokyo underground venue location, lineup names in crisp bold sans-serif type, textured risograph print texture on raw uncoated cotton stock, museum exhibition graphic art --ar 2:3 --v 6.1",
    safePreviewText: "Graphic design poster in the authentic International Typographic Style (Swiss Style)...",
    tags: ["Swiss Style", "Poster", "Typography", "Music", "Geometric", "Minimalist"],
    difficulty: "Beginner",
    style: "International Typographic",
    mood: "Bold & Iconic",
    recommendedTools: [
      {
        toolId: "tool-midjourney",
        toolName: "Midjourney",
        modelName: "Midjourney v6.1",
        reason: "Superb paper grain textures, risograph ink bleed, and geometric abstraction",
        badge: "Best Art Quality",
      },
      {
        toolId: "tool-canva-magic",
        toolName: "Canva Magic Studio",
        modelName: "Magic Design 2026",
        reason: "Easy post-processing to edit line-up artist text directly onto the poster",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Prompt in Midjourney",
        instruction: "Keep the `--ar 2:3` flag for authentic vertical poster proportion.",
      },
      {
        stepNumber: 2,
        title: "Import into Canva or Illustrator",
        instruction: "If you need customized lineup text, import the upscaled artwork into Canva or Illustrator to overlay exact typography.",
      },
      {
        stepNumber: 3,
        title: "Print Ready",
        instruction: "Export as high-DPI PDF ready for physical screenprinting or digital promotion.",
      },
    ],
    thumbnailGradient: "from-rose-700 via-stone-900 to-amber-950",
    likesCount: 1530,
    savesCount: 1180,
    isPublished: true,
    createdAt: "2026-03-02T13:45:00Z",
  },
  {
    id: "template-poster-brand-identity",
    name: "Eco-Friendly Brand Identity Board & Packaging",
    slug: "eco-friendly-brand-identity-board",
    categoryId: "cat-poster-design",
    categoryName: "Poster & Design",
    subcategoryId: "sub-poster-branding",
    subcategoryName: "Brandboards & Visual Identity",
    description: "Complete visual identity brandboard prompt containing logo mark options, earthy color palette swatches, botanical typography, and embossed kraft box packaging.",
    promptText: "Professional graphic design brand identity presentation board for an organic botanical apothecary brand. Clean multi-panel layout showing: 1) Minimalist embossed olive leaf icon monogram logo. 2) 5 curated earthy color swatches (sage green, terracotta, unbleached linen, dark forest, soft clay) with CMYK hex labels. 3) Font specimen pairing elegant high-contrast serif and clean editorial grotesque sans. 4) 3D mockup of kraft paper dropper bottle and embossed cardboard shipping box on stone slab. Soft top-down studio lighting, clean brand agency portfolio presentation --ar 16:9 --v 6.1",
    safePreviewText: "Professional graphic design brand identity presentation board for an organic botanical apothecary...",
    tags: ["Branding", "Identity", "Packaging", "Eco", "Monogram"],
    difficulty: "Intermediate",
    style: "Brand Guidelines Board",
    mood: "Organic & Luxurious",
    recommendedTools: [
      {
        toolId: "tool-midjourney",
        toolName: "Midjourney",
        modelName: "Midjourney v6.1",
        reason: "Renders lifelike packaging textures and foil embossings",
        badge: "Top Choice",
      },
      {
        toolId: "tool-flux",
        toolName: "Flux",
        modelName: "FLUX.1 Pro",
        reason: "Crisp letterforms on monogram logo options",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Run Prompt",
        instruction: "Generate in 16:9 ratio to view the multi-panel board layout.",
      },
      {
        stepNumber: 2,
        title: "Isolate Logo & Packaging",
        instruction: "Select the most cohesive brand palette and crop individual elements for your style guide.",
      },
    ],
    thumbnailGradient: "from-stone-600 via-emerald-950 to-amber-950",
    likesCount: 790,
    savesCount: 620,
    isPublished: true,
    createdAt: "2026-03-04T17:10:00Z",
  },
  {
    id: "template-poster-synthwave",
    name: "Retro 80s Synthwave Nightclub Flyer",
    slug: "retro-80s-synthwave-flyer",
    categoryId: "cat-poster-design",
    categoryName: "Poster & Design",
    subcategoryId: "sub-poster-retro",
    subcategoryName: "Retro & Synthwave",
    description: "High-octane 1980s outrun aesthetic with chrome typography, perspective neon wireframe grid, and glowing horizon sunset.",
    promptText: "Retro 1980s synthwave outrun event flyer. Chrome beveled typography with hot magenta neon outline, glowing digital wireframe grid road receding into a low purple horizon, massive segmented orange neon wireframe sun setting behind palm tree silhouettes. Starfield sky with cyan laser beams, VHS glitch cassette tape sleeve texture, screenprinted 80s arcade aesthetic --ar 2:3 --v 6.1",
    safePreviewText: "Retro 1980s synthwave outrun event flyer. Chrome beveled typography with hot magenta neon...",
    tags: ["Retro", "Synthwave", "80s", "Neon", "Flyer", "Chrome"],
    difficulty: "Beginner",
    style: "Outrun Synthwave",
    mood: "Nostalgic & High-Energy",
    recommendedTools: [
      {
        toolId: "tool-midjourney",
        toolName: "Midjourney",
        modelName: "Midjourney v6.1",
        reason: "Luminous neon glows and authentic vintage VHS tape artifacts",
        badge: "Recommended",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Generate Poster",
        instruction: "Use `/imagine` with `--ar 2:3` for flyer dimensions.",
      },
      {
        stepNumber: 2,
        title: "Upscale & Share",
        instruction: "Upscale your favorite wireframe grid variant and export.",
      },
    ],
    thumbnailGradient: "from-fuchsia-900 via-purple-900 to-amber-600",
    likesCount: 1220,
    savesCount: 850,
    isPublished: true,
    createdAt: "2026-03-05T20:00:00Z",
  },
  {
    id: "template-slides-keynote-launch",
    name: "AI Product Keynote & Launch Presentation",
    slug: "ai-product-keynote-launch-presentation",
    categoryId: "cat-slides-presentations",
    categoryName: "Slides & Presentations",
    subcategoryId: "sub-slides-keynote",
    subcategoryName: "Keynotes & Product Launches",
    description: "Cinematic keynote slide template with bold typography, dark glassmorphism device mockups, and impactful punchy transitions.",
    promptText: "Design an 8-slide high-impact Apple-style AI product launch keynote presentation deck. Minimalist dark obsidian background with subtle neon gradient radial glow. Slide structure: 1) Teaser: 'One More Thing' minimalist typography. 2) Problem Statement: Full-bleed statement slide with 72pt condensed bold serif type. 3) Product Reveal: 3D hardware device floating with ambient light halo. 4) Architecture Diagram: Clean node system with glowing neon connection paths. 5) 3 Benchmark Metrics: Giant numeric callouts (10x Faster, 99.4% Precision, 0 Latency). 6) Live Demo Screen Preview. 7) Developer Ecosystem & Pricing. 8) Availability & Launch CTA. Clean, zero clutter, high emotional resonance.",
    safePreviewText: "Design an 8-slide high-impact Apple-style AI product launch keynote presentation deck...",
    tags: ["Slides", "Keynote", "Launch", "Presentation", "Ai", "All", "Recent"],
    difficulty: "Beginner",
    style: "Cinematic Keynote",
    mood: "Bold & Visionary",
    recommendedTools: [
      {
        toolId: "tool-gamma",
        toolName: "Gamma",
        modelName: "Gamma Keynote AI",
        reason: "Generates high-contrast dark keynote slides instantly",
        badge: "Top Keynote Tool",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Import into Gamma or Beautiful.ai",
        instruction: "Select 16:9 widescreen format for maximum cinematic impact.",
      },
      {
        stepNumber: 2,
        title: "Insert Product Visuals",
        instruction: "Drop in your 3D product renders or app UI screenshots into the mockup frames.",
      },
    ],
    thumbnailGradient: "from-indigo-950 via-purple-950 to-slate-950",
    likesCount: 1420,
    savesCount: 1120,
    isPublished: true,
    createdAt: "2026-03-09T10:00:00Z",
  },
  {
    id: "template-slides-vc-series-a",
    name: "Series A SaaS Growth & Investor Pitch Deck",
    slug: "series-a-saas-growth-pitch-deck",
    categoryId: "cat-slides-presentations",
    categoryName: "Slides & Presentations",
    subcategoryId: "sub-slides-pitch",
    subcategoryName: "Pitch Decks & Fundraising",
    description: "Data-heavy Series A fundraising presentation deck with ARR growth trajectory charts, cohort retention curves, and unit economics.",
    promptText: "Create a rigorous 12-slide Series A venture capital pitch deck for an enterprise SaaS startup raising $12M. Clean navy-black theme with mint green and cyan financial highlights. Essential slides: 1) Cover slide with vision statement. 2) $5M ARR Inflection Curve: Clean line chart with milestone annotations. 3) Net Revenue Retention: 140% NRR cohort heatmap table. 4) Enterprise Customer Wall: Fortune 500 logo grid. 5) Product moat and network effects. 6) Go-To-Market efficiency: CAC payback < 8 months. 7) Competitive 2x2 matrix. 8) Pro-forma revenue projections for next 3 years. 9) Executive team and hiring roadmap. 10) Use of funds allocation waterfall. Clean sans-serif typography, data-dense without clutter.",
    safePreviewText: "Create a rigorous 12-slide Series A venture capital pitch deck for an enterprise SaaS startup...",
    tags: ["Slides", "Pitch Deck", "Investor", "Saas", "Fintech", "All", "Recent"],
    difficulty: "Advanced",
    style: "Data-Dense Financial",
    mood: "Authoritative & Rapid Growth",
    recommendedTools: [
      {
        toolId: "tool-gamma",
        toolName: "Gamma",
        modelName: "Gamma Presentation AI",
        reason: "Handles complex tables, cohort heatmaps, and financial metrics effortlessly",
        badge: "VC Standard",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Load Template",
        instruction: "Use Gamma's document-to-presentation generator.",
      },
      {
        stepNumber: 2,
        title: "Connect Financials",
        instruction: "Replace chart coordinates with your actual Stripe or ChartMogul metrics.",
      },
    ],
    thumbnailGradient: "from-teal-950 via-slate-900 to-emerald-950",
    likesCount: 980,
    savesCount: 840,
    isPublished: true,
    createdAt: "2026-03-09T14:00:00Z",
  },
  {
    id: "template-poster-brutalist-art",
    name: "Brutalist Bauhaus Exhibition Art Poster",
    slug: "brutalist-bauhaus-exhibition-art-poster",
    categoryId: "cat-poster-design",
    categoryName: "Poster & Design",
    subcategoryId: "sub-poster-events",
    subcategoryName: "Music & Cultural Events",
    description: "Raw architectural brutalist exhibition poster with stark sans-serif typography, concrete textures, and asymmetric geometry.",
    promptText: "Museum exhibition poster in the raw neo-brutalist graphic design style. Heavy oversized black typography in bold Neue Haas Grotesk, massive asymmetric architectural concrete beam graphic intersecting a crimson red circle, textured paper fold creases, raw industrial aesthetics, Berlin contemporary art gallery dates and catalog numbers, risograph ink texture on unbleached recycled cardstock --ar 2:3 --v 6.1",
    safePreviewText: "Museum exhibition poster in the raw neo-brutalist graphic design style...",
    tags: ["Poster", "Bauhaus", "Brutalist", "Typography", "Creative", "All", "Recent"],
    difficulty: "Beginner",
    style: "Neo-Brutalist",
    mood: "Stark & Architectural",
    recommendedTools: [
      {
        toolId: "tool-midjourney",
        toolName: "Midjourney",
        modelName: "Midjourney v6.1",
        reason: "Unmatched concrete textures, paper creases, and risograph bleed",
        badge: "Best Quality",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Generate in Midjourney",
        instruction: "Run prompt with `--ar 2:3` for classic poster vertical aspect ratio.",
      },
      {
        stepNumber: 2,
        title: "Export & Print",
        instruction: "Upscale with Creative Upscaler and print at 300 DPI.",
      },
    ],
    thumbnailGradient: "from-stone-900 via-red-950 to-neutral-900",
    likesCount: 1670,
    savesCount: 1290,
    isPublished: true,
    createdAt: "2026-03-09T16:00:00Z",
  },
  {
    id: "template-video-cyber-city",
    name: "Cyberpunk Tokyo Aerial Drone Night Loop",
    slug: "cyberpunk-tokyo-aerial-drone-night-loop",
    categoryId: "cat-video-gen",
    categoryName: "Video Generation",
    subcategoryId: "sub-vid-cinematic",
    subcategoryName: "Cinematic & B-Roll",
    description: "Mesmerizing 4K cinematic FPV drone flight descending through neon skyscrapers, flying vehicles, and rain-slicked Tokyo streets.",
    promptText: "Cinematic 4K FPV drone continuous shot diving down through a rain-slicked futuristic Tokyo metropolis at midnight. Towering neon holographic billboards advertising cybernetics, glowing magenta and electric blue light trails from flying mag-lev traffic, heavy atmospheric mist and volumetric steam rising from street grates, reflections in wet asphalt, anamorphic lens flare, motion blur, smooth 60fps pacing, hyper-realistic cinematic photorealism --ar 16:9 --motion 6",
    safePreviewText: "Cinematic 4K FPV drone continuous shot diving down through a rain-slicked futuristic Tokyo...",
    tags: ["Video Generation", "Cinematic", "Drone", "Cyberpunk", "Technology", "All", "Recent"],
    difficulty: "Intermediate",
    style: "Cyberpunk Sci-Fi",
    mood: "Cinematic & Immersive",
    recommendedTools: [
      {
        toolId: "tool-runway",
        toolName: "Runway",
        modelName: "Gen-3 Alpha",
        reason: "Exceptional volumetric lighting and coherent drone camera movement",
        badge: "Flagship Match",
      },
    ],
    usageSteps: [
      {
        stepNumber: 1,
        title: "Input into Runway Gen-3 or Sora",
        instruction: "Set camera motion to Forward + Down with high fidelity prompt weight.",
      },
      {
        stepNumber: 2,
        title: "Export Seamless Loop",
        instruction: "Render in 4K resolution at 60fps for background video loops.",
      },
    ],
    thumbnailGradient: "from-fuchsia-950 via-blue-950 to-purple-950",
    likesCount: 2150,
    savesCount: 1760,
    isPublished: true,
    createdAt: "2026-03-09T18:00:00Z",
  },
];
