import { AITool } from "../types";

export const initialAITools: AITool[] = [
  {
    id: "tool-midjourney",
    name: "Midjourney",
    vendor: "Midjourney Inc.",
    description: "Industry-leading image generation with unmatched lighting nuance, photorealism, and artistic aesthetic.",
    category: "Image",
    isRetired: false,
    externalUrl: "https://midjourney.com",
    models: [
      { id: "mj-v6-1", name: "Midjourney v6.1", isDefault: true },
      { id: "mj-v6", name: "Midjourney v6" },
      { id: "mj-niji-6", name: "Niji 6 (Anime/Illustration)" },
    ],
  },
  {
    id: "tool-runway",
    name: "Runway",
    vendor: "Runway AI, Inc.",
    description: "Pioneering generative video system with advanced motion brush, camera control, and multi-second coherence.",
    category: "Video",
    isRetired: false,
    externalUrl: "https://runwayml.com",
    models: [
      { id: "runway-gen3-turbo", name: "Runway Gen-3 Alpha Turbo", isDefault: true },
      { id: "runway-gen3", name: "Runway Gen-3 Alpha" },
      { id: "runway-gen2", name: "Runway Gen-2" },
    ],
  },
  {
    id: "tool-sora",
    name: "OpenAI Sora",
    vendor: "OpenAI",
    description: "High-fidelity video generation capable of complex physical simulation and photorealistic motion.",
    category: "Video",
    isRetired: false,
    externalUrl: "https://openai.com/sora",
    models: [
      { id: "sora-v1", name: "Sora 1.0 (Direct API)", isDefault: true },
    ],
  },
  {
    id: "tool-pika",
    name: "Pika",
    vendor: "Pika Labs",
    description: "Dynamic video tool with intuitive physics effects, camera pans, and speed ramps.",
    category: "Video",
    isRetired: false,
    externalUrl: "https://pika.art",
    models: [
      { id: "pika-1-5", name: "Pika 1.5", isDefault: true },
      { id: "pika-1-0", name: "Pika 1.0" },
    ],
  },
  {
    id: "tool-flux",
    name: "Flux",
    vendor: "Black Forest Labs",
    description: "Open-weight state-of-the-art image generator with crisp typography rendering and anatomical precision.",
    category: "Image",
    isRetired: false,
    externalUrl: "https://blackforestlabs.ai",
    models: [
      { id: "flux-schnell", name: "FLUX.1 Schnell", isDefault: true },
      { id: "flux-dev", name: "FLUX.1 Dev" },
      { id: "flux-pro", name: "FLUX.1 Pro" },
    ],
  },
  {
    id: "tool-sdxl",
    name: "Stable Diffusion",
    vendor: "Stability AI",
    description: "Highly customizable open model with deep ControlNet ecosystem and LoRA fine-tuning flexibility.",
    category: "Image",
    isRetired: false,
    externalUrl: "https://stability.ai",
    models: [
      { id: "sdxl-1-0", name: "SDXL 1.0", isDefault: true },
      { id: "sd-3-5", name: "Stable Diffusion 3.5 Large" },
    ],
  },
  {
    id: "tool-v0",
    name: "v0 by Vercel",
    vendor: "Vercel",
    description: "Generative UI system producing production-ready React, Tailwind CSS, and shadcn/ui components.",
    category: "Code / Web",
    isRetired: false,
    externalUrl: "https://v0.dev",
    models: [
      { id: "v0-react", name: "v0 React / Tailwind", isDefault: true },
    ],
  },
  {
    id: "tool-lovable",
    name: "Lovable",
    vendor: "Lovable",
    description: "Full-stack AI web app builder with instant Supabase backend, live previews, and one-click deployment.",
    category: "Code / Web",
    isRetired: false,
    externalUrl: "https://lovable.dev",
    models: [
      { id: "lovable-fullstack", name: "Lovable Fullstack", isDefault: true },
    ],
  },
  {
    id: "tool-bolt",
    name: "Bolt.new",
    vendor: "StackBlitz",
    description: "In-browser WebContainer development environment capable of full-stack Node/Vite app scaffolding.",
    category: "Code / Web",
    isRetired: false,
    externalUrl: "https://bolt.new",
    models: [
      { id: "bolt-webcontainer", name: "Bolt WebContainer 2.0", isDefault: true },
    ],
  },
  {
    id: "tool-stitch",
    name: "Google Stitch",
    vendor: "Google",
    description: "AI-assisted design-to-code and screen synthesis tool for creating coherent design system tokens and screens.",
    category: "Code / Web",
    isRetired: false,
    externalUrl: "https://stitch.withgoogle.com",
    models: [
      { id: "stitch-v1", name: "Stitch Screen Generator", isDefault: true },
    ],
  },
  {
    id: "tool-framer-ai",
    name: "Framer AI",
    vendor: "Framer B.V.",
    description: "Visual web design generator that produces responsive, animated websites ready to publish with one click.",
    category: "Code / Web",
    isRetired: false,
    externalUrl: "https://framer.com",
    models: [
      { id: "framer-layout-engine", name: "Framer AI 2.0", isDefault: true },
    ],
  },
  {
    id: "tool-cursor",
    name: "Cursor",
    vendor: "Anysphere",
    description: "AI-first code editor with Composer multi-file generation, terminal execution, and deep codebase indexing.",
    category: "Code / Web",
    isRetired: false,
    externalUrl: "https://cursor.com",
    models: [
      { id: "cursor-sonnet", name: "Claude 3.7 Sonnet", isDefault: true },
      { id: "cursor-gpt4o", name: "GPT-4o", isDefault: false },
    ],
  },
  {
    id: "tool-antigravity",
    name: "Antigravity",
    vendor: "Google DeepMind",
    description: "Agentic AI coding assistant with autonomous planning, multi-file code editing, and dev server verification.",
    category: "Code / Web",
    isRetired: false,
    externalUrl: "https://antigravity.google",
    models: [
      { id: "antigravity-v2", name: "Antigravity 2.0 Agent", isDefault: true },
    ],
  },
  {
    id: "tool-replit",
    name: "Replit Agent",
    vendor: "Replit",
    description: "Autonomous software development agent that builds, tests, and deploys full-stack web applications.",
    category: "Code / Web",
    isRetired: false,
    externalUrl: "https://replit.com",
    models: [
      { id: "replit-agent-v1", name: "Replit Agent", isDefault: true },
    ],
  },
  {
    id: "tool-webflow-ai",
    name: "Webflow AI",
    vendor: "Webflow",
    description: "Visual web development platform with AI-generated layouts, CMS collections, and enterprise hosting.",
    category: "Code / Web",
    isRetired: false,
    externalUrl: "https://webflow.com",
    models: [
      { id: "webflow-ai-site", name: "Webflow Site Generator", isDefault: true },
    ],
  },
  {
    id: "tool-wix-ai",
    name: "Wix Studio AI",
    vendor: "Wix",
    description: "Proportional fluid responsive site generator with integrated business applications and ecommerce.",
    category: "Code / Web",
    isRetired: false,
    externalUrl: "https://wix.com/studio",
    models: [
      { id: "wix-studio-ai", name: "Wix Studio Generator", isDefault: true },
    ],
  },
  {
    id: "tool-claude",
    name: "Claude",
    vendor: "Anthropic",
    description: "State-of-the-art reasoning model for architectural planning, clean React code generation, and debugging.",
    category: "Code / Web",
    isRetired: false,
    externalUrl: "https://claude.ai",
    models: [
      { id: "claude-3-7-sonnet", name: "Claude 3.7 Sonnet", isDefault: true },
    ],
  },
  {
    id: "tool-gamma",
    name: "Gamma",
    vendor: "Gamma App",
    description: "AI-powered presentation creator that generates formatted cards, visual layouts, and pitch decks.",
    category: "Design / Slides",
    isRetired: false,
    externalUrl: "https://gamma.app",
    models: [
      { id: "gamma-pro", name: "Gamma Presentation AI", isDefault: true },
    ],
  },
  {
    id: "tool-canva-magic",
    name: "Canva Magic Studio",
    vendor: "Canva",
    description: "Accessible design suite with AI layout generation for marketing banners, posters, and social graphics.",
    category: "Design / Slides",
    isRetired: false,
    externalUrl: "https://canva.com",
    models: [
      { id: "canva-magic-design", name: "Magic Design 2026", isDefault: true },
    ],
  },
  {
    id: "tool-beautiful-ai",
    name: "Beautiful.ai",
    vendor: "Beautiful.ai",
    description: "Design-led presentation software with Smart Slide templates, automatic adaptive formatting, and corporate themes.",
    category: "Design / Slides",
    isRetired: false,
    externalUrl: "https://beautiful.ai",
    models: [
      { id: "designer-bot", name: "DesignerBot 2026", isDefault: true },
    ],
  },
  {
    id: "tool-copilot-ppt",
    name: "Microsoft Copilot (PowerPoint)",
    vendor: "Microsoft",
    description: "Enterprise slide generation with Word-to-PowerPoint narrative synthesis, Designer layouts, and Microsoft 365 integration.",
    category: "Design / Slides",
    isRetired: false,
    externalUrl: "https://copilot.microsoft.com",
    models: [
      { id: "copilot-m365", name: "Copilot for Microsoft 365", isDefault: true },
    ],
  },
  {
    id: "tool-gemini-slides",
    name: "Google Slides (Gemini)",
    vendor: "Google",
    description: "Native Google Workspace presentation generator with Docs-to-Slides synthesis, Duet AI imagery, and Drive collaboration.",
    category: "Design / Slides",
    isRetired: false,
    externalUrl: "https://workspace.google.com",
    models: [
      { id: "gemini-workspace", name: "Gemini for Google Workspace", isDefault: true },
    ],
  },
  {
    id: "tool-tome",
    name: "Tome",
    vendor: "Tome",
    description: "Storytelling AI presentation builder with generative text, 3D interactive embeds, and fluid multimedia layouts.",
    category: "Design / Slides",
    isRetired: false,
    externalUrl: "https://tome.app",
    models: [
      { id: "tome-ai", name: "Tome Story AI", isDefault: true },
    ],
  },
  {
    id: "tool-pitch",
    name: "Pitch",
    vendor: "Pitch Software GmbH",
    description: "Collaborative presentation workspace with AI deck generation, modern typography blocks, and async video recordings.",
    category: "Design / Slides",
    isRetired: false,
    externalUrl: "https://pitch.com",
    models: [
      { id: "pitch-generator", name: "Pitch 2.0 AI Builder", isDefault: true },
    ],
  },
  {
    id: "tool-plus-ai",
    name: "Plus AI",
    vendor: "PlusDocs",
    description: "AI presentation and slide deck maker add-on for Google Slides and Microsoft PowerPoint.",
    category: "Design / Slides",
    isRetired: false,
    externalUrl: "https://plusdocs.com",
    models: [
      { id: "plus-ai-v2", name: "Plus AI Engine", isDefault: true },
    ],
  },
  {
    id: "tool-slides-ai",
    name: "SlidesAI",
    vendor: "SlidesAI.io",
    description: "AI-powered text-to-presentation tool that summarizes long content into formatted slides directly in Google Slides.",
    category: "Design / Slides",
    isRetired: false,
    externalUrl: "https://slidesai.io",
    models: [
      { id: "slides-ai-v2", name: "SlidesAI Engine", isDefault: true },
    ],
  },
  {
    id: "tool-prezi-ai",
    name: "Prezi AI",
    vendor: "Prezi Inc.",
    description: "Dynamic visual storytelling platform with spatial zooming canvases, topic clusters, and live video presentations.",
    category: "Design / Slides",
    isRetired: false,
    externalUrl: "https://prezi.com",
    models: [
      { id: "prezi-ai-v1", name: "Prezi AI Story Engine", isDefault: true },
    ],
  },
  {
    id: "tool-adobe-express",
    name: "Adobe Express",
    vendor: "Adobe",
    description: "Quick creative design app with Firefly generative AI, template remixing, Adobe Fonts, and one-click resizing.",
    category: "Poster & Design",
    isRetired: false,
    externalUrl: "https://www.adobe.com/express/",
    models: [
      { id: "express-firefly-v3", name: "Adobe Express (Firefly 3)", isDefault: true },
    ],
  },
  {
    id: "tool-adobe-firefly",
    name: "Adobe Firefly",
    vendor: "Adobe",
    description: "Commercially safe generative AI engine specialized in text effects, generative match, and high-fidelity poster composition.",
    category: "Poster & Design",
    isRetired: false,
    externalUrl: "https://firefly.adobe.com",
    models: [
      { id: "firefly-image-3", name: "Firefly Image 3", isDefault: true },
    ],
  },
  {
    id: "tool-ideogram",
    name: "Ideogram",
    vendor: "Ideogram AI",
    description: "State-of-the-art AI design engine renowned for reliable typographic spelling, typography style tags, and poster aesthetics.",
    category: "Poster & Design",
    isRetired: false,
    externalUrl: "https://ideogram.ai",
    models: [
      { id: "ideogram-v2", name: "Ideogram 2.0", isDefault: true },
      { id: "ideogram-v1", name: "Ideogram 1.0" },
    ],
  },
  {
    id: "tool-kittl",
    name: "Kittl",
    vendor: "Kittl",
    description: "Intuitive graphic design platform with AI layout generation, advanced vector text warping, and vintage/modern textures.",
    category: "Poster & Design",
    isRetired: false,
    externalUrl: "https://www.kittl.com",
    models: [
      { id: "kittl-ai-v2", name: "Kittl AI Design Engine", isDefault: true },
    ],
  },
  {
    id: "tool-ms-designer",
    name: "Microsoft Designer",
    vendor: "Microsoft",
    description: "AI-powered graphic design app that creates social posts, invitations, digital postcards, and graphics from text prompts.",
    category: "Poster & Design",
    isRetired: false,
    externalUrl: "https://designer.microsoft.com",
    models: [
      { id: "ms-designer-copilot", name: "Designer Copilot (DALL-E 3)", isDefault: true },
    ],
  },
  {
    id: "tool-figma-ai",
    name: "Figma AI",
    vendor: "Figma",
    description: "Collaborative design environment with AI first drafts, auto-layout scaffolding, and production design system tokens.",
    category: "Poster & Design",
    isRetired: false,
    externalUrl: "https://figma.com",
    models: [
      { id: "figma-first-draft", name: "Figma AI First Draft", isDefault: true },
    ],
  },
];


