import { AITool } from "../types";

export const initialAITools: AITool[] = [
  {
    id: "tool-midjourney",
    name: "Midjourney",
    vendor: "Midjourney Inc.",
    description: "Industry-leading image generation with unmatched lighting nuance, photorealism, and artistic aesthetic.",
    category: "Image",
    isRetired: false,
    externalUrl: "https://midjourney.com",
    models: [
      { id: "mj-v6-1", name: "Midjourney v6.1", isDefault: true },
      { id: "mj-v6", name: "Midjourney v6" },
      { id: "mj-niji-6", name: "Niji 6 (Anime/Illustration)" },
    ],
  },
  {
    id: "tool-runway",
    name: "Runway",
    vendor: "Runway AI, Inc.",
    description: "Pioneering generative video system with advanced motion brush, camera control, and multi-second coherence.",
    category: "Video",
    isRetired: false,
    externalUrl: "https://runwayml.com",
    models: [
      { id: "runway-gen3-turbo", name: "Runway Gen-3 Alpha Turbo", isDefault: true },
      { id: "runway-gen3", name: "Runway Gen-3 Alpha" },
      { id: "runway-gen2", name: "Runway Gen-2" },
    ],
  },
  {
    id: "tool-sora",
    name: "OpenAI Sora",
    vendor: "OpenAI",
    description: "High-fidelity video generation capable of complex physical simulation and photorealistic motion.",
    category: "Video",
    isRetired: false,
    externalUrl: "https://openai.com/sora",
    models: [
      { id: "sora-v1", name: "Sora 1.0 (Direct API)", isDefault: true },
    ],
  },
  {
    id: "tool-pika",
    name: "Pika",
    vendor: "Pika Labs",
    description: "Dynamic video tool with intuitive physics effects, camera pans, and speed ramps.",
    category: "Video",
    isRetired: false,
    externalUrl: "https://pika.art",
    models: [
      { id: "pika-1-5", name: "Pika 1.5", isDefault: true },
      { id: "pika-1-0", name: "Pika 1.0" },
    ],
  },
  {
    id: "tool-flux",
    name: "Flux",
    vendor: "Black Forest Labs",
    description: "Open-weight state-of-the-art image generator with crisp typography rendering and anatomical precision.",
    category: "Image",
    isRetired: false,
    externalUrl: "https://blackforestlabs.ai",
    models: [
      { id: "flux-schnell", name: "FLUX.1 Schnell", isDefault: true },
      { id: "flux-dev", name: "FLUX.1 Dev" },
      { id: "flux-pro", name: "FLUX.1 Pro" },
    ],
  },
  {
    id: "tool-sdxl",
    name: "Stable Diffusion",
    vendor: "Stability AI",
    description: "Highly customizable open model with deep ControlNet ecosystem and LoRA fine-tuning flexibility.",
    category: "Image",
    isRetired: false,
    externalUrl: "https://stability.ai",
    models: [
      { id: "sdxl-1-0", name: "SDXL 1.0", isDefault: true },
      { id: "sd-3-5", name: "Stable Diffusion 3.5 Large" },
    ],
  },
  {
    id: "tool-v0",
    name: "v0 by Vercel",
    vendor: "Vercel",
    description: "Generative UI system producing production-ready React, Tailwind CSS, and shadcn/ui components.",
    category: "Code / Web",
    isRetired: false,
    externalUrl: "https://v0.dev",
    models: [
      { id: "v0-react", name: "v0 React / Tailwind", isDefault: true },
    ],
  },
  {
    id: "tool-framer-ai",
    name: "Framer AI",
    vendor: "Framer B.V.",
    description: "Visual web design generator that produces responsive, animated websites ready to publish with one click.",
    category: "Code / Web",
    isRetired: false,
    externalUrl: "https://framer.com",
    models: [
      { id: "framer-layout-engine", name: "Framer AI 2.0", isDefault: true },
    ],
  },
  {
    id: "tool-gamma",
    name: "Gamma",
    vendor: "Gamma App",
    description: "AI-powered presentation creator that generates formatted cards, visual layouts, and pitch decks.",
    category: "Design / Slides",
    isRetired: false,
    externalUrl: "https://gamma.app",
    models: [
      { id: "gamma-pro", name: "Gamma Presentation AI", isDefault: true },
    ],
  },
  {
    id: "tool-canva-magic",
    name: "Canva Magic Studio",
    vendor: "Canva",
    description: "Accessible design suite with AI layout generation for marketing banners, posters, and social graphics.",
    category: "Design / Slides",
    isRetired: false,
    externalUrl: "https://canva.com",
    models: [
      { id: "canva-magic-design", name: "Magic Design 2026", isDefault: true },
    ],
  },
];
